// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;

    [Source("LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightHudView")]
    public partial class DroneFlightHudView
    {
        public override string Address => "LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightHudView";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private CanvasGroup CanvasGroup_DroneFlightHudView;
        private TextMeshProUGUI TextMeshProUGUI_FlightText;
        private TextMeshProUGUI TextMeshProUGUI_CameraText;
        private TextMeshProUGUI TextMeshProUGUI_PayloadText;
        private TextMeshProUGUI TextMeshProUGUI_WarningText;
        private TextMeshProUGUI TextMeshProUGUI_ControlsText;
        private TextMeshProUGUI TextMeshProUGUI_ControlsHeaderText;
        private TextMeshProUGUI TextMeshProUGUI_FlightControlsText;
        private TextMeshProUGUI TextMeshProUGUI_CameraControlsText;
        private TextMeshProUGUI TextMeshProUGUI_SystemControlsText;
        private Image Image_ResetProgressFill;
        private TextMeshProUGUI TextMeshProUGUI_ResetProgressText;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            CanvasGroup_DroneFlightHudView = componentItemIndex.Get<CanvasGroup>(0);
            TextMeshProUGUI_FlightText = componentItemIndex.Get<TextMeshProUGUI>(1);
            TextMeshProUGUI_CameraText = componentItemIndex.Get<TextMeshProUGUI>(2);
            TextMeshProUGUI_PayloadText = componentItemIndex.Get<TextMeshProUGUI>(3);
            TextMeshProUGUI_WarningText = componentItemIndex.Get<TextMeshProUGUI>(4);
            TextMeshProUGUI_ControlsText = componentItemIndex.Get<TextMeshProUGUI>(5);
            TextMeshProUGUI_ControlsHeaderText = componentItemIndex.Get<TextMeshProUGUI>(6);
            TextMeshProUGUI_FlightControlsText = componentItemIndex.Get<TextMeshProUGUI>(7);
            TextMeshProUGUI_CameraControlsText = componentItemIndex.Get<TextMeshProUGUI>(8);
            TextMeshProUGUI_SystemControlsText = componentItemIndex.Get<TextMeshProUGUI>(9);
            Image_ResetProgressFill = componentItemIndex.Get<Image>(10);
            TextMeshProUGUI_ResetProgressText = componentItemIndex.Get<TextMeshProUGUI>(11);
        }
    }
}
