// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;

    [Source("LoadResources/Demos/dlss/Prefabs/DlssSettingsView")]
    public partial class DlssSettingsView
    {
        public override string Address => "LoadResources/Demos/dlss/Prefabs/DlssSettingsView";
        public override UILayer Level => UILayer.Base;
        public override UIViewMode ViewMode => UIViewMode.Page;
        public override MaskType Mask => MaskType.None;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private RawImage RawImage_WorldImage;
        private TextMeshProUGUI TextMeshProUGUI_DeviceText;
        private TextMeshProUGUI TextMeshProUGUI_ModeText;
        private Button Button_OffButton;
        private Button Button_QualityButton;
        private Button Button_BalancedButton;
        private Button Button_PerformanceButton;
        private Button Button_UltraPerformanceButton;
        private Button Button_DlaaButton;
        private TextMeshProUGUI TextMeshProUGUI_ResolutionText;
        private TextMeshProUGUI TextMeshProUGUI_StatusText;
        private Button Button_ResetCameraButton;
        private Button Button_BackButton;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            RawImage_WorldImage = componentItemIndex.Get<RawImage>(0);
            TextMeshProUGUI_DeviceText = componentItemIndex.Get<TextMeshProUGUI>(1);
            TextMeshProUGUI_ModeText = componentItemIndex.Get<TextMeshProUGUI>(2);
            Button_OffButton = componentItemIndex.Get<Button>(3);
            Button_QualityButton = componentItemIndex.Get<Button>(4);
            Button_BalancedButton = componentItemIndex.Get<Button>(5);
            Button_PerformanceButton = componentItemIndex.Get<Button>(6);
            Button_UltraPerformanceButton = componentItemIndex.Get<Button>(7);
            Button_DlaaButton = componentItemIndex.Get<Button>(8);
            TextMeshProUGUI_ResolutionText = componentItemIndex.Get<TextMeshProUGUI>(9);
            TextMeshProUGUI_StatusText = componentItemIndex.Get<TextMeshProUGUI>(10);
            Button_ResetCameraButton = componentItemIndex.Get<Button>(11);
            Button_BackButton = componentItemIndex.Get<Button>(12);
            this.RegisterButton(Button_OffButton, OnOffButtonClick);
            this.RegisterButton(Button_QualityButton, OnQualityButtonClick);
            this.RegisterButton(Button_BalancedButton, OnBalancedButtonClick);
            this.RegisterButton(Button_PerformanceButton, OnPerformanceButtonClick);
            this.RegisterButton(Button_UltraPerformanceButton, OnUltraPerformanceButtonClick);
            this.RegisterButton(Button_DlaaButton, OnDlaaButtonClick);
            this.RegisterButton(Button_ResetCameraButton, OnResetCameraButtonClick);
            this.RegisterButton(Button_BackButton, OnBackButtonClick);
        }
    }
}
