using System.Collections.Generic;

namespace Core.Editor.TextMeshPro
{
    internal enum TMPFontBuilderEditorLanguage
    {
        Chinese,
        English
    }

    internal enum TMPFontBuilderText
    {
        WindowTitle,
        Presets,
        Preset,
        PresetName,
        AddPresetTooltip,
        RemovePresetTooltip,
        MovePresetUpTooltip,
        MovePresetDownTooltip,
        LoadPreset,
        SavePreset,
        Source,
        FontFile,
        OutputDirectory,
        OutputDirectoryTooltip,
        Output,
        FileNameSuffix,
        FileNameSuffixTooltip,
        Characters,
        CharacterSetText,
        AdditionalCharacters,
        ExtractCharacters,
        Fallback,
        FallbackFont,
        PreserveExistingFallback,
        PreserveExistingFallbackTooltip,
        Generation,
        SamplingPointSize,
        SamplingPointSizeTooltip,
        AtlasPadding,
        AtlasPaddingTooltip,
        AtlasSize,
        AtlasSizeTooltip,
        OptimalPacking,
        OptimalPackingTooltip,
        ExportExternalAtlas,
        ExportExternalAtlasTooltip,
        AstcPlatformSettings,
        AstcPlatformSettingsTooltip,
        OutputPreview,
        OutputPreviewHint,
        BuildFontAsset,
        LoadedPreset,
        SavedPreset,
        AddedPreset,
        RemovedPreset,
        CannotRemoveLastPreset,
        EmptyPresetName,
        DuplicatePresetName,
        EmptyOutputDirectory,
        InvalidOutputDirectory,
        InvalidFileNameSuffix,
        InvalidSamplingPointSize,
        InvalidAtlasPadding,
        InvalidAtlasSize,
        InvalidPreset,
        UnsavedChangesTitle,
        UnsavedChangesMessage,
        Save,
        Discard,
        Cancel,
        DeletePresetTitle,
        DeletePresetMessage,
        Delete,
        FallbackIgnored,
        SelectSourceFont,
        SelectCharacterSet,
        UpdateFontTitle,
        UpdateFontMessage,
        Update,
        EmptyCharacterSet,
        BuildCompleted,
        BuildCompletedMissing,
        BuildFailed,
        CharacterSetAlreadyContained,
        CharacterSetMerged,
        CharacterSetWriteFailed,
        NoExistingFont,
        ExtractCompleted,
        ExtractNoMissing,
        GenerationProgressTitle,
        GenerationProgressMessage
    }

    internal static class TMPFontBuilderLocalization
    {
        private static readonly Dictionary<TMPFontBuilderText, string[]> Texts = new Dictionary<TMPFontBuilderText, string[]>
        {
            { TMPFontBuilderText.WindowTitle, new[] { "TMP 字体生成器", "TMP Font Builder" } },
            { TMPFontBuilderText.Presets, new[] { "预设", "Presets" } },
            { TMPFontBuilderText.Preset, new[] { "当前预设", "Preset" } },
            { TMPFontBuilderText.PresetName, new[] { "预设名称", "Preset Name" } },
            { TMPFontBuilderText.AddPresetTooltip, new[] { "复制当前参数并新增预设", "Duplicate current settings as a new preset" } },
            { TMPFontBuilderText.RemovePresetTooltip, new[] { "删除当前预设", "Remove the selected preset" } },
            { TMPFontBuilderText.MovePresetUpTooltip, new[] { "上移当前预设", "Move the selected preset up" } },
            { TMPFontBuilderText.MovePresetDownTooltip, new[] { "下移当前预设", "Move the selected preset down" } },
            { TMPFontBuilderText.LoadPreset, new[] { "加载预设", "Load Preset" } },
            { TMPFontBuilderText.SavePreset, new[] { "保存预设", "Save Preset" } },
            { TMPFontBuilderText.Source, new[] { "源字体", "Source" } },
            { TMPFontBuilderText.FontFile, new[] { "字体文件", "Font File" } },
            { TMPFontBuilderText.OutputDirectory, new[] { "输出目录", "Output Directory" } },
            { TMPFontBuilderText.OutputDirectoryTooltip, new[] { "当前预设生成到 TMP_FontAssets 下的子目录，例如 Japanese 或 Arabic", "Subfolder under TMP_FontAssets for this preset, such as Japanese or Arabic" } },
            { TMPFontBuilderText.Output, new[] { "输出", "Output" } },
            { TMPFontBuilderText.FileNameSuffix, new[] { "文件名后缀", "File Name Suffix" } },
            { TMPFontBuilderText.FileNameSuffixTooltip, new[] { "追加到源字体名称后；已有相同后缀时不会重复追加", "Appended to the source font name unless it already ends with the suffix" } },
            { TMPFontBuilderText.Characters, new[] { "字符", "Characters" } },
            { TMPFontBuilderText.CharacterSetText, new[] { "字符集文本", "Character Set Text" } },
            { TMPFontBuilderText.AdditionalCharacters, new[] { "追加字符（生成时合并到字符集）", "Additional Characters (merged into the character set on build)" } },
            { TMPFontBuilderText.ExtractCharacters, new[] { "从已有 TMP 字体及 Fallback 提取字符差异", "Extract character differences from existing TMP font and fallbacks" } },
            { TMPFontBuilderText.Fallback, new[] { "回退字体", "Fallback" } },
            { TMPFontBuilderText.FallbackFont, new[] { "回退字体资产", "Fallback Font" } },
            { TMPFontBuilderText.PreserveExistingFallback, new[] { "空值时保留原 Fallback", "Preserve Existing Fallback When Empty" } },
            { TMPFontBuilderText.PreserveExistingFallbackTooltip, new[] { "更新已有字体且当前预设未指定 Fallback 时，保留字体原有的 Fallback 列表", "When updating an existing font with no preset fallback, keep its current fallback list" } },
            { TMPFontBuilderText.Generation, new[] { "生成参数", "Generation" } },
            { TMPFontBuilderText.SamplingPointSize, new[] { "采样字号", "Sampling Point Size" } },
            { TMPFontBuilderText.SamplingPointSizeTooltip, new[] { "生成 SDF 字形时的采样字号，必须大于 0；越大细节越清晰，但占用图集空间越多", "SDF sampling size; must be greater than 0. Larger values improve detail but use more atlas space" } },
            { TMPFontBuilderText.AtlasPadding, new[] { "图集间距", "Atlas Padding" } },
            { TMPFontBuilderText.AtlasPaddingTooltip, new[] { "字形间的像素边距，必须大于等于 0；描边和发光通常需要更大间距", "Pixel spacing between glyphs; must be non-negative. Outlines and glow usually need more padding" } },
            { TMPFontBuilderText.AtlasSize, new[] { "图集尺寸", "Atlas Size" } },
            { TMPFontBuilderText.AtlasSizeTooltip, new[] { "只允许 256～4096 的 2 次幂", "Must be a power of two between 256 and 4096" } },
            { TMPFontBuilderText.OptimalPacking, new[] { "紧密装箱（Optimum）", "Optimal Packing" } },
            { TMPFontBuilderText.OptimalPackingTooltip, new[] { "使用 ContactPointRule 减少图集空隙；生成较慢，但能容纳更多字形", "Uses ContactPointRule to reduce empty atlas space; slower, but can fit more glyphs" } },
            { TMPFontBuilderText.ExportExternalAtlas, new[] { "导出外部图集", "Export External Atlas" } },
            { TMPFontBuilderText.ExportExternalAtlasTooltip, new[] { "将 Atlas 导出为独立 PNG，便于查看和单独设置压缩", "Exports the atlas as a separate PNG for inspection and independent compression settings" } },
            { TMPFontBuilderText.AstcPlatformSettings, new[] { "应用 ASTC 平台设置", "ASTC Platform Settings" } },
            { TMPFontBuilderText.AstcPlatformSettingsTooltip, new[] { "为 Android 和 iPhone 应用 ASTC 6x6 高质量压缩", "Applies ASTC 6x6 high-quality compression on Android and iPhone" } },
            { TMPFontBuilderText.OutputPreview, new[] { "输出预览", "Output Preview" } },
            { TMPFontBuilderText.OutputPreviewHint, new[] { "选择源字体并填写有效输出目录后显示最终路径。", "Select a source font and valid output directory to preview final paths." } },
            { TMPFontBuilderText.BuildFontAsset, new[] { "生成 TMP 字体资产", "Build TMP Font Asset" } },
            { TMPFontBuilderText.LoadedPreset, new[] { "已加载预设：{0}", "Loaded preset: {0}" } },
            { TMPFontBuilderText.SavedPreset, new[] { "已保存预设：{0}", "Saved preset: {0}" } },
            { TMPFontBuilderText.AddedPreset, new[] { "已新增预设：{0}", "Added preset: {0}" } },
            { TMPFontBuilderText.RemovedPreset, new[] { "已删除预设：{0}", "Removed preset: {0}" } },
            { TMPFontBuilderText.CannotRemoveLastPreset, new[] { "至少需要保留一套预设。", "At least one preset must remain." } },
            { TMPFontBuilderText.EmptyPresetName, new[] { "预设名称不能为空。", "Preset name cannot be empty." } },
            { TMPFontBuilderText.DuplicatePresetName, new[] { "预设名称不能重复。", "Preset name must be unique." } },
            { TMPFontBuilderText.EmptyOutputDirectory, new[] { "输出目录不能为空。", "Output directory cannot be empty." } },
            { TMPFontBuilderText.InvalidOutputDirectory, new[] { "输出目录只能是单个合法文件夹名称。", "Output directory must be one valid folder name." } },
            { TMPFontBuilderText.InvalidFileNameSuffix, new[] { "文件名后缀包含非法字符。", "File name suffix contains invalid characters." } },
            { TMPFontBuilderText.InvalidSamplingPointSize, new[] { "采样字号必须大于 0。", "Sampling point size must be greater than 0." } },
            { TMPFontBuilderText.InvalidAtlasPadding, new[] { "图集间距不能小于 0。", "Atlas padding cannot be negative." } },
            { TMPFontBuilderText.InvalidAtlasSize, new[] { "图集尺寸必须是 256 至 4096 之间的 2 次幂。", "Atlas size must be a power of two between 256 and 4096." } },
            { TMPFontBuilderText.InvalidPreset, new[] { "当前预设无效，请重新选择。", "The selected preset is invalid. Select it again." } },
            { TMPFontBuilderText.UnsavedChangesTitle, new[] { "未保存的预设修改", "Unsaved Preset Changes" } },
            { TMPFontBuilderText.UnsavedChangesMessage, new[] { "预设“{0}”包含未保存的修改。", "Preset \"{0}\" has unsaved changes." } },
            { TMPFontBuilderText.Save, new[] { "保存", "Save" } },
            { TMPFontBuilderText.Discard, new[] { "放弃", "Discard" } },
            { TMPFontBuilderText.Cancel, new[] { "取消", "Cancel" } },
            { TMPFontBuilderText.DeletePresetTitle, new[] { "删除预设", "Delete Preset" } },
            { TMPFontBuilderText.DeletePresetMessage, new[] { "确定删除预设“{0}”吗？", "Delete preset \"{0}\"?" } },
            { TMPFontBuilderText.Delete, new[] { "删除", "Delete" } },
            { TMPFontBuilderText.FallbackIgnored, new[] { "当前回退字体指向正在生成的同一份字体，已自动忽略。", "The fallback points to the font being generated and was ignored." } },
            { TMPFontBuilderText.SelectSourceFont, new[] { "请选择源字体。", "Select a source font." } },
            { TMPFontBuilderText.SelectCharacterSet, new[] { "请选择字符集文件；追加字符会合并写入该文件。", "Select a character set file; additional characters will be merged into it." } },
            { TMPFontBuilderText.UpdateFontTitle, new[] { "更新 TMP 字体", "Update TMP Font" } },
            { TMPFontBuilderText.UpdateFontMessage, new[] { "目标字体已存在，将保留 GUID 并更新内容：\n{0}", "The target font already exists. Its GUID will be preserved while content is updated:\n{0}" } },
            { TMPFontBuilderText.Update, new[] { "更新", "Update" } },
            { TMPFontBuilderText.EmptyCharacterSet, new[] { "字符集为空，已取消生成。", "The character set is empty. Build cancelled." } },
            { TMPFontBuilderText.BuildCompleted, new[] { "字体生成完成：{0}{1}", "Font generated: {0}{1}" } },
            { TMPFontBuilderText.BuildCompletedMissing, new[] { "字体已生成，但存在缺字：{0}{1}", "Font generated with missing characters: {0}{1}" } },
            { TMPFontBuilderText.BuildFailed, new[] { "字体生成失败：{0}", "Font generation failed: {0}" } },
            { TMPFontBuilderText.CharacterSetAlreadyContained, new[] { "\n追加字符均已存在于字符集。", "\nAll additional characters already exist in the character set." } },
            { TMPFontBuilderText.CharacterSetMerged, new[] { "\n已合并并去重写入字符集：{0}", "\nMerged, deduplicated, and saved to character set: {0}" } },
            { TMPFontBuilderText.CharacterSetWriteFailed, new[] { "写入字符集失败：{0}", "Failed to write character set: {0}" } },
            { TMPFontBuilderText.NoExistingFont, new[] { "没有找到已生成的目标 TMP 字体，也没有配置 Fallback 字体。", "No generated target TMP font or configured fallback font was found." } },
            { TMPFontBuilderText.ExtractCompleted, new[] { "已检查 {0} 个 TMP 字体，发现 {1} 个字符未记录在字符集；已填入追加字符栏。", "Checked {0} TMP fonts and added {1} characters missing from the character set." } },
            { TMPFontBuilderText.ExtractNoMissing, new[] { "已检查 {0} 个 TMP 字体，字符集没有遗漏。", "Checked {0} TMP fonts; the character set has no omissions." } },
            { TMPFontBuilderText.GenerationProgressTitle, new[] { "TMP 字体生成", "TMP Font Generation" } },
            { TMPFontBuilderText.GenerationProgressMessage, new[] { "正在进行紧密装箱，字符较多时需要等待……", "Optimal packing in progress; large character sets may take time..." } }
        };

        internal static string Get(TMPFontBuilderText key, TMPFontBuilderEditorLanguage language)
        {
            return Texts.TryGetValue(key, out var values) ? values[(int)language] : key.ToString();
        }

        internal static string Format(TMPFontBuilderText key, TMPFontBuilderEditorLanguage language, params object[] args)
        {
            return string.Format(Get(key, language), args);
        }

        internal static bool HasTranslation(TMPFontBuilderText key, TMPFontBuilderEditorLanguage language)
        {
            return Texts.TryGetValue(key, out var values)
                && values.Length > (int)language
                && !string.IsNullOrWhiteSpace(values[(int)language]);
        }
    }
}
