// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.BlockPorters;

    [Source("LoadResources/Demos/block_porters/Prefabs/UI/BlockPortersResultView")]
    public partial class BlockPortersResultView
    {
        public override string Address => "LoadResources/Demos/block_porters/Prefabs/UI/BlockPortersResultView";
        public override UILayer Level => UILayer.Tip;
        public override UIViewMode ViewMode => UIViewMode.Modal;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private BlockPortersResultPresenter BlockPortersResultPresenter_BlockPortersResultView;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            BlockPortersResultPresenter_BlockPortersResultView = componentItemIndex.Get<BlockPortersResultPresenter>(0);
        }
    }
}
