// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;

    [Source("LoadResources/Demos/block_porters/Prefabs/UI/BlockPortersResultView")]
    public partial class BlockPortersResultView
    {
        public override string Address => "LoadResources/Demos/block_porters/Prefabs/UI/BlockPortersResultView";
        public override UILayer Level => UILayer.Tip;
        public override UIViewMode ViewMode => UIViewMode.Modal;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private TextMeshProUGUI TextMeshProUGUI_ResultTitle;
        private TextMeshProUGUI TextMeshProUGUI_ResultDescription;
        private Button Button_Next;
        private TextMeshProUGUI TextMeshProUGUI_NextLabel;
        private Button Button_ResultRestart;
        private Button Button_ResultExit;
        private Button Button_ResultUnlock0;
        private Button Button_ResultUnlock1;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            TextMeshProUGUI_ResultTitle = componentItemIndex.Get<TextMeshProUGUI>(0);
            TextMeshProUGUI_ResultDescription = componentItemIndex.Get<TextMeshProUGUI>(1);
            Button_Next = componentItemIndex.Get<Button>(2);
            TextMeshProUGUI_NextLabel = componentItemIndex.Get<TextMeshProUGUI>(3);
            Button_ResultRestart = componentItemIndex.Get<Button>(4);
            Button_ResultExit = componentItemIndex.Get<Button>(5);
            Button_ResultUnlock0 = componentItemIndex.Get<Button>(6);
            Button_ResultUnlock1 = componentItemIndex.Get<Button>(7);
        }
    }
}
