// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.JinxCasino.UI;

    [Source("LoadResources/Demos/jinx_casino/Prefabs/UI/JinxCasinoPauseView")]
    public partial class JinxCasinoPauseView
    {
        public override string Address => "LoadResources/Demos/jinx_casino/Prefabs/UI/JinxCasinoPauseView";
        public override UILayer Level => UILayer.Tip;
        public override UIViewMode ViewMode => UIViewMode.Modal;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private JinxCasinoPausePresenter JinxCasinoPausePresenter_JinxCasinoPauseView;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            JinxCasinoPausePresenter_JinxCasinoPauseView = componentItemIndex.Get<JinxCasinoPausePresenter>(0);
        }
    }
}
