using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;

namespace Core.Editor.Config
{
    public readonly struct LubanTableDescriptor
    {
        /// <summary>
        /// 创建一条由生成管理器源码发现的表描述。
        /// </summary>
        /// <param name="propertyName">生成管理器中的表属性名。</param>
        /// <param name="propertyType">生成表包装类型。</param>
        /// <param name="dataFileName">Luban loader 使用的数据文件名。</param>
        public LubanTableDescriptor(string propertyName, string propertyType, string dataFileName)
        {
            PropertyName = propertyName;
            PropertyType = propertyType;
            DataFileName = dataFileName;
        }

        /// 生成管理器中的表属性名。
        public string PropertyName { get; }

        /// 生成表包装类型。
        public string PropertyType { get; }

        /// Luban loader 使用的数据文件名。
        public string DataFileName { get; }
    }

    public static class LubanTemplateClassGenerator
    {
        /// 默认的 Luban 生成管理器路径。
        public const string DefaultGeneratedManagerPath = "Assets/Scripts/Hotfix/Cfgs/Generated/GeneratedTables.cs";

        /// 默认的静态 Tables facade 输出路径。
        public const string DefaultOutputPath = "Assets/Scripts/Hotfix/Cfgs/TablesPartial.cs";

        private static readonly Regex PropertyPattern = new Regex(
            @"public\s+(?<type>[A-Za-z_][A-Za-z0-9_.<>]*)\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*\{\s*get;\s*\}",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        private static readonly Regex LoaderPattern = new Regex(
            @"(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*new\s+[A-Za-z_][A-Za-z0-9_.<>]*\s*\(\s*loader\(""(?<file>[^""]+)""\)\s*\)\s*;",
            RegexOptions.Compiled | RegexOptions.CultureInvariant);

        /// <summary>
        /// 从 Luban 生成的管理器源码中发现表属性与对应数据文件。
        /// </summary>
        /// <param name="generatedManagerPath">GeneratedTables.cs 的文件路径。</param>
        /// <returns>按属性名稳定排序的表描述列表。</returns>
        public static IReadOnlyList<LubanTableDescriptor> DiscoverTables(string generatedManagerPath)
        {
            if (string.IsNullOrWhiteSpace(generatedManagerPath) || !File.Exists(generatedManagerPath))
            {
                throw new FileNotFoundException("未找到 Luban 生成管理器源码。", generatedManagerPath);
            }

            var source = File.ReadAllText(generatedManagerPath);
            var loaders = LoaderPattern.Matches(source)
                .Cast<Match>()
                .ToDictionary(
                    match => match.Groups["name"].Value,
                    match => match.Groups["file"].Value,
                    StringComparer.Ordinal);

            var descriptors = PropertyPattern.Matches(source)
                .Cast<Match>()
                .Select(match =>
                {
                    var propertyName = match.Groups["name"].Value;
                    if (!loaders.TryGetValue(propertyName, out var dataFileName))
                    {
                        throw new InvalidDataException($"表属性 {propertyName} 缺少对应 loader 数据文件。路径：{generatedManagerPath}");
                    }

                    return new LubanTableDescriptor(
                        propertyName,
                        match.Groups["type"].Value,
                        dataFileName);
                })
                .OrderBy(descriptor => descriptor.PropertyName, StringComparer.Ordinal)
                .ToArray();

            if (descriptors.Length == 0)
            {
                throw new InvalidDataException($"Luban 生成管理器中未发现任何表：{generatedManagerPath}");
            }

            return descriptors;
        }

        /// <summary>
        /// 生成静态 Tables facade 源码。
        /// </summary>
        /// <param name="tables">已发现且校验通过的表描述。</param>
        /// <returns>确定性排序的完整 C# 源码。</returns>
        public static string GenerateSource(IReadOnlyList<LubanTableDescriptor> tables)
        {
            if (tables == null || tables.Count == 0)
            {
                throw new InvalidDataException("不能为 0 张表生成 Tables facade。");
            }

            var sortedTables = tables.OrderBy(table => table.PropertyName, StringComparer.Ordinal).ToArray();
            var builder = new StringBuilder();
            builder.AppendLine("//------------------------------------------------------------------------------");
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("//     Generated by SleepyDemos LubanTemplateClassGenerator.");
            builder.AppendLine("//     Do not edit this file manually.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine("//------------------------------------------------------------------------------");
            builder.AppendLine();
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using Luban;");
            builder.AppendLine();
            builder.AppendLine("namespace Cfg");
            builder.AppendLine("{");
            builder.AppendLine("    public static partial class Tables");
            builder.AppendLine("    {");
            builder.AppendLine("        private static readonly string[] dataFileNames =");
            builder.AppendLine("        {");
            foreach (var table in sortedTables)
            {
                builder.AppendLine($"            \"{table.DataFileName}\",");
            }
            builder.AppendLine("        };");
            builder.AppendLine();
            builder.AppendLine("        private static GeneratedTables instance;");
            builder.AppendLine();
            builder.AppendLine("        /// 配置是否已经完整初始化。");
            builder.AppendLine("        public static bool IsInitialized => instance != null;");
            builder.AppendLine();
            builder.AppendLine("        /// 当前配置预加载进度。");
            builder.AppendLine("        public static float LoadProgress { get; private set; }");
            builder.AppendLine();
            builder.AppendLine("        /// 当前生成表数量。");
            builder.AppendLine("        public static int TableCount => dataFileNames.Length;");
            foreach (var table in sortedTables)
            {
                builder.AppendLine();
                builder.AppendLine($"        /// {table.PropertyName} 配置表。");
                builder.AppendLine($"        public static {table.PropertyType} {table.PropertyName} => Instance.{table.PropertyName};");
            }
            builder.AppendLine();
            builder.AppendLine("        internal static IReadOnlyList<string> DataFileNames => dataFileNames;");
            builder.AppendLine();
            builder.AppendLine("        internal static GeneratedTables CreateGeneratedTables(Func<string, ByteBuf> loader)");
            builder.AppendLine("        {");
            builder.AppendLine("            return new GeneratedTables(loader);");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        internal static void SetInstance(GeneratedTables value)");
            builder.AppendLine("        {");
            builder.AppendLine("            instance = value ?? throw new ArgumentNullException(nameof(value));");
            builder.AppendLine("            LoadProgress = 1f;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        internal static void SetLoadProgress(float value)");
            builder.AppendLine("        {");
            builder.AppendLine("            LoadProgress = value;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        internal static void ResetAfterFailure()");
            builder.AppendLine("        {");
            builder.AppendLine("            instance = null;");
            builder.AppendLine("            LoadProgress = 0f;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static GeneratedTables Instance => instance ?? throw new InvalidOperationException(");
            builder.AppendLine("            \"Luban 配置尚未初始化。请确认 LubanConfigSystem 已在业务访问 Tables 前完成。资源目录：LoadResources/Config/Luban。\");");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString().Replace("\r\n", "\n");
        }

        /// 使用默认路径重新生成 TablesPartial.cs；内容无变化时不写盘。
        public static bool GenerateDefault()
        {
            var tables = DiscoverTables(DefaultGeneratedManagerPath);
            var source = GenerateSource(tables);
            var outputDirectory = Path.GetDirectoryName(DefaultOutputPath);
            if (!string.IsNullOrEmpty(outputDirectory))
            {
                Directory.CreateDirectory(outputDirectory);
            }

            var existing = File.Exists(DefaultOutputPath)
                ? File.ReadAllText(DefaultOutputPath).Replace("\r\n", "\n")
                : null;
            if (string.Equals(existing, source, StringComparison.Ordinal))
            {
                return false;
            }

            File.WriteAllText(DefaultOutputPath, source, new UTF8Encoding(false));
            AssetDatabase.Refresh();
            return true;
        }
    }
}
