// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Core.Runtime.Inputs;

    [Source("LoadResources/UI/Common/SimpleTips")]
    public partial class SimpleTipsView
    {
        public override string Address => "LoadResources/UI/Common/SimpleTips";
        public override UILayer Level => UILayer.Tip;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => false;
        public override bool DestroyOnHide => false;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private UITipsPanel UITipsPanel_SimpleTips;
        private UITooltip UITooltip_SimpleTips;
        private UIMenuScope UIMenuScope_SimpleTips;
        private Button Button_Blocker;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            UITipsPanel_SimpleTips = componentItemIndex.Get<UITipsPanel>(0);
            UITooltip_SimpleTips = componentItemIndex.Get<UITooltip>(1);
            UIMenuScope_SimpleTips = componentItemIndex.Get<UIMenuScope>(2);
            Button_Blocker = componentItemIndex.Get<Button>(3);
        }
    }
}
