// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;

    [Source("LoadResources/UI/MainMenuView")]
    public partial class MainMenuView
    {
        public override string Address => "LoadResources/UI/MainMenuView";
        public override UILayer Level => UILayer.Base;
        public override MaskType Mask => MaskType.None;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => false;

        private Image imageBackground;
        private Text textTitle;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            imageBackground = componentItemIndex.Get<Image>(0);
            textTitle = componentItemIndex.Get<Text>(1);
        }
    }
}
