// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.WallSqueeze;

    [Source("LoadResources/Demos/wall_squeeze/Prefabs/UI/WallSqueezeHudView")]
    public partial class WallSqueezeHudView
    {
        public override string Address => "LoadResources/Demos/wall_squeeze/Prefabs/UI/WallSqueezeHudView";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private WallSqueezeHudPanel WallSqueezeHudPanel_WallSqueezeHudView;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            WallSqueezeHudPanel_WallSqueezeHudView = componentItemIndex.Get<WallSqueezeHudPanel>(0);
        }
    }
}
