// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.JinxCasino.UI;

    [Source("LoadResources/Demos/jinx_casino/Prefabs/UI/JinxCasinoImmersionHudView")]
    public partial class JinxCasinoImmersionHudView
    {
        public override string Address => "LoadResources/Demos/jinx_casino/Prefabs/UI/JinxCasinoImmersionHudView";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private JinxCasinoImmersionHudPresenter JinxCasinoImmersionHudPresenter_JinxCasinoImmersionHudView;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            JinxCasinoImmersionHudPresenter_JinxCasinoImmersionHudView = componentItemIndex.Get<JinxCasinoImmersionHudPresenter>(0);
        }
    }
}
