// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;

    public partial class TestView : View
    {
        public override string Address => "LoadResources/UI/TestView";
        public override UILayer Level => UILayer.Base;
        public override MaskType Mask => MaskType.None;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;

        private Button buttonCloseButton;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            buttonCloseButton = componentItemIndex.Get<Button>(0);
            this.RegisterButton(buttonCloseButton, OnCloseButtonClick);
        }
    }
}
