// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.JinxCasino.Adapters.UI;

    [Source("LoadResources/Demos/jinx_casino/Prefabs/UI/JinxCasinoHudView")]
    public partial class JinxCasinoHudView
    {
        public override string Address => "LoadResources/Demos/jinx_casino/Prefabs/UI/JinxCasinoHudView";
        public override UILayer Level => UILayer.Base;
        public override UIViewMode ViewMode => UIViewMode.Page;
        public override MaskType Mask => MaskType.None;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;

        private JinxCasinoHudPresenter JinxCasinoHudPresenter_JinxCasinoHudView;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            JinxCasinoHudPresenter_JinxCasinoHudView = componentItemIndex.Get<JinxCasinoHudPresenter>(0);
        }
    }
}
