// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Core.Runtime.Inputs;
    using TMPro;

    [Source("LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightVehicleSelectView")]
    public partial class DroneFlightVehicleSelectView
    {
        public override string Address => "LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightVehicleSelectView";
        public override UILayer Level => UILayer.Pop;
        public override UIViewMode ViewMode => UIViewMode.Modal;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private UIMenuScope UIMenuScope_DroneFlightVehicleSelectView;
        private Image Image_Hero;
        private TextMeshProUGUI TextMeshProUGUI_Title;
        private TextMeshProUGUI TextMeshProUGUI_Description;
        private TextMeshProUGUI TextMeshProUGUI_Equipment;
        private TextMeshProUGUI TextMeshProUGUI_Operation;
        private TextMeshProUGUI TextMeshProUGUI_Purpose;
        private Image Image_PlainButton;
        private Button Button_PlainButton;
        private UIState UIState_PlainButton;
        private Image Image_PlainPreview;
        private RectTransform RectTransform_PlainSelected;
        private Image Image_GrappleButton;
        private Button Button_GrappleButton;
        private UIState UIState_GrappleButton;
        private Image Image_GrapplePreview;
        private RectTransform RectTransform_GrappleSelected;
        private Image Image_HarpoonButton;
        private Button Button_HarpoonButton;
        private UIState UIState_HarpoonButton;
        private Image Image_HarpoonPreview;
        private RectTransform RectTransform_HarpoonSelected;
        private Button Button_StartButton;
        private TextMeshProUGUI TextMeshProUGUI_StartLabel;
        private TextMeshProUGUI TextMeshProUGUI_Status;
        private Button Button_BackButton;
        private RectTransform RectTransform_Hints;
        private TextMeshProUGUI TextMeshProUGUI_MoveHint;
        private TextMeshProUGUI TextMeshProUGUI_TouchHint;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            UIMenuScope_DroneFlightVehicleSelectView = componentItemIndex.Get<UIMenuScope>(0);
            Image_Hero = componentItemIndex.Get<Image>(1);
            TextMeshProUGUI_Title = componentItemIndex.Get<TextMeshProUGUI>(2);
            TextMeshProUGUI_Description = componentItemIndex.Get<TextMeshProUGUI>(3);
            TextMeshProUGUI_Equipment = componentItemIndex.Get<TextMeshProUGUI>(4);
            TextMeshProUGUI_Operation = componentItemIndex.Get<TextMeshProUGUI>(5);
            TextMeshProUGUI_Purpose = componentItemIndex.Get<TextMeshProUGUI>(6);
            Image_PlainButton = componentItemIndex.Get<Image>(7);
            Button_PlainButton = componentItemIndex.Get<Button>(8);
            UIState_PlainButton = componentItemIndex.Get<UIState>(9);
            Image_PlainPreview = componentItemIndex.Get<Image>(10);
            RectTransform_PlainSelected = componentItemIndex.Get<RectTransform>(11);
            Image_GrappleButton = componentItemIndex.Get<Image>(12);
            Button_GrappleButton = componentItemIndex.Get<Button>(13);
            UIState_GrappleButton = componentItemIndex.Get<UIState>(14);
            Image_GrapplePreview = componentItemIndex.Get<Image>(15);
            RectTransform_GrappleSelected = componentItemIndex.Get<RectTransform>(16);
            Image_HarpoonButton = componentItemIndex.Get<Image>(17);
            Button_HarpoonButton = componentItemIndex.Get<Button>(18);
            UIState_HarpoonButton = componentItemIndex.Get<UIState>(19);
            Image_HarpoonPreview = componentItemIndex.Get<Image>(20);
            RectTransform_HarpoonSelected = componentItemIndex.Get<RectTransform>(21);
            Button_StartButton = componentItemIndex.Get<Button>(22);
            TextMeshProUGUI_StartLabel = componentItemIndex.Get<TextMeshProUGUI>(23);
            TextMeshProUGUI_Status = componentItemIndex.Get<TextMeshProUGUI>(24);
            Button_BackButton = componentItemIndex.Get<Button>(25);
            RectTransform_Hints = componentItemIndex.Get<RectTransform>(26);
            TextMeshProUGUI_MoveHint = componentItemIndex.Get<TextMeshProUGUI>(27);
            TextMeshProUGUI_TouchHint = componentItemIndex.Get<TextMeshProUGUI>(28);
            this.RegisterButton(Button_PlainButton, OnPlainButtonClick);
            this.RegisterButton(Button_GrappleButton, OnGrappleButtonClick);
            this.RegisterButton(Button_HarpoonButton, OnHarpoonButtonClick);
            this.RegisterButton(Button_StartButton, OnStartButtonClick);
            this.RegisterButton(Button_BackButton, OnBackButtonClick);
        }
    }
}
