// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Core.Runtime.Inputs;
    using TMPro;

    [Source("LoadResources/Demos/jinx_casino/Prefabs/UI/JinxCasinoEndingView")]
    public partial class JinxCasinoEndingView
    {
        public override string Address => "LoadResources/Demos/jinx_casino/Prefabs/UI/JinxCasinoEndingView";
        public override UILayer Level => UILayer.Tip;
        public override UIViewMode ViewMode => UIViewMode.Modal;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private UICancelRelay UICancelRelay_JinxCasinoEndingView;
        private RectTransform RectTransform_StandardEnding;
        private TextMeshProUGUI TextMeshProUGUI_Title;
        private TextMeshProUGUI TextMeshProUGUI_Message;
        private TextMeshProUGUI TextMeshProUGUI_Stats;
        private TextMeshProUGUI TextMeshProUGUI_Profile;
        private Button Button_Save;
        private Button Button_ReturnToHub;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            UICancelRelay_JinxCasinoEndingView = componentItemIndex.Get<UICancelRelay>(0);
            RectTransform_StandardEnding = componentItemIndex.Get<RectTransform>(1);
            TextMeshProUGUI_Title = componentItemIndex.Get<TextMeshProUGUI>(2);
            TextMeshProUGUI_Message = componentItemIndex.Get<TextMeshProUGUI>(3);
            TextMeshProUGUI_Stats = componentItemIndex.Get<TextMeshProUGUI>(4);
            TextMeshProUGUI_Profile = componentItemIndex.Get<TextMeshProUGUI>(5);
            Button_Save = componentItemIndex.Get<Button>(6);
            Button_ReturnToHub = componentItemIndex.Get<Button>(7);
        }
    }
}
