// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Core.Runtime.Inputs;
    using TMPro;

    [Source("LoadResources/Demos/jinx_casino/Prefabs/UI/JinxCasinoMainMenuView")]
    public partial class JinxCasinoMainMenuView
    {
        public override string Address => "LoadResources/Demos/jinx_casino/Prefabs/UI/JinxCasinoMainMenuView";
        public override UILayer Level => UILayer.Tip;
        public override UIViewMode ViewMode => UIViewMode.Modal;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private UICancelRelay UICancelRelay_JinxCasinoMainMenuView;
        private RectTransform RectTransform_MainMenu;
        private Button Button_Start;
        private Button Button_Practice;
        private TextMeshProUGUI TextMeshProUGUI_Footer;
        private Button Button_Tutorial;
        private Button Button_LoadAdventure;
        private Button Button_Settings;
        private Button Button_QuitGame;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            UICancelRelay_JinxCasinoMainMenuView = componentItemIndex.Get<UICancelRelay>(0);
            RectTransform_MainMenu = componentItemIndex.Get<RectTransform>(1);
            Button_Start = componentItemIndex.Get<Button>(2);
            Button_Practice = componentItemIndex.Get<Button>(3);
            TextMeshProUGUI_Footer = componentItemIndex.Get<TextMeshProUGUI>(4);
            Button_Tutorial = componentItemIndex.Get<Button>(5);
            Button_LoadAdventure = componentItemIndex.Get<Button>(6);
            Button_Settings = componentItemIndex.Get<Button>(7);
            Button_QuitGame = componentItemIndex.Get<Button>(8);
        }
    }
}
