// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.BlockPorters;

    [Source("LoadResources/Demos/block_porters/Prefabs/UI/BlockPortersHudView")]
    public partial class BlockPortersHudView
    {
        public override string Address => "LoadResources/Demos/block_porters/Prefabs/UI/BlockPortersHudView";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private BlockPortersHudPresenter BlockPortersHudPresenter_BlockPortersHudView;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            BlockPortersHudPresenter_BlockPortersHudView = componentItemIndex.Get<BlockPortersHudPresenter>(0);
        }
    }
}
