// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;

    [Source("LoadResources/UI/pfb&TestView")]
    public partial class TestView
    {
        public override string Address => "LoadResources/UI/pfb&TestView";
        public override UILayer Level => UILayer.Base;
        public override MaskType Mask => MaskType.None;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;

        private TextMeshProUGUI TextMeshProUGUI_Title;
        private Button Button_AddButton;
        private Button Button_CloseButton;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            TextMeshProUGUI_Title = componentItemIndex.Get<TextMeshProUGUI>(0);
            Button_AddButton = componentItemIndex.Get<Button>(1);
            Button_CloseButton = componentItemIndex.Get<Button>(2);
            this.RegisterButton(Button_AddButton, OnAddButtonClick);
            this.RegisterButton(Button_CloseButton, OnCloseButtonClick);
        }
    }
}
