// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.WallSqueeze;

    [Source("LoadResources/Demos/wall_squeeze/Prefabs/UI/WallSqueezeMenuView")]
    public partial class WallSqueezeMenuView
    {
        public override string Address => "LoadResources/Demos/wall_squeeze/Prefabs/UI/WallSqueezeMenuView";
        public override UILayer Level => UILayer.Pop;
        public override UIViewMode ViewMode => UIViewMode.Modal;
        public override MaskType Mask => MaskType.ShowOnly;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private WallSqueezeMenuPanel WallSqueezeMenuPanel_WallSqueezeMenuView;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            WallSqueezeMenuPanel_WallSqueezeMenuView = componentItemIndex.Get<WallSqueezeMenuPanel>(0);
        }
    }
}
