// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.HowToFish;

    [Source("LoadResources/Demos/how_to_fish/Prefabs/UI/HowToFishMainMenuView")]
    public partial class HowToFishMainMenuView
    {
        public override string Address => "LoadResources/Demos/how_to_fish/Prefabs/UI/HowToFishMainMenuView";
        public override UILayer Level => UILayer.Tip;
        public override UIViewMode ViewMode => UIViewMode.Modal;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private HowToFishMainMenuPresenter HowToFishMainMenuPresenter_HowToFishMainMenuView;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            HowToFishMainMenuPresenter_HowToFishMainMenuView = componentItemIndex.Get<HowToFishMainMenuPresenter>(0);
        }
    }
}
