// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;

    [Source("LoadResources/UI/Common/CommonTips")]
    public partial class CommonTipsView
    {
        public override string Address => "LoadResources/UI/Common/CommonTips";
        public override UILayer Level => UILayer.Tip;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => false;
        public override bool DestroyOnHide => false;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private UITipsStack UITipsStack_CommonTips;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            UITipsStack_CommonTips = componentItemIndex.Get<UITipsStack>(0);
        }
    }
}
