//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by SleepyDemos LubanTemplateClassGenerator.
//     Do not edit this file manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Luban;

namespace Cfg
{
    public static partial class Tables
    {
        private static readonly string[] dataFileNames =
        {
            "example_info",
        };

        private static GeneratedTables instance;

        /// 配置是否已经完整初始化。
        public static bool IsInitialized => instance != null;

        /// 当前配置预加载进度。
        public static float LoadProgress { get; private set; }

        /// 当前生成表数量。
        public static int TableCount => dataFileNames.Length;

        /// ExampleInfo 配置表。
        public static ExampleInfo ExampleInfo => Instance.ExampleInfo;

        internal static IReadOnlyList<string> DataFileNames => dataFileNames;

        internal static GeneratedTables CreateGeneratedTables(Func<string, ByteBuf> loader)
        {
            return new GeneratedTables(loader);
        }

        internal static void SetInstance(GeneratedTables value)
        {
            instance = value ?? throw new ArgumentNullException(nameof(value));
            LoadProgress = 1f;
        }

        internal static void SetLoadProgress(float value)
        {
            LoadProgress = value;
        }

        internal static void ResetAfterFailure()
        {
            instance = null;
            LoadProgress = 0f;
        }

        private static GeneratedTables Instance => instance ?? throw new InvalidOperationException(
            "Luban 配置尚未初始化。请确认 LubanConfigSystem 已在业务访问 Tables 前完成。资源目录：LoadResources/Config/Luban。");
    }
}
