// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Core.Runtime.Inputs;
    using TMPro;

    [Source("LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightHelpView")]
    public partial class DroneFlightHelpView
    {
        public override string Address => "LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightHelpView";
        public override UILayer Level => UILayer.Tip;
        public override UIViewMode ViewMode => UIViewMode.Modal;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private TextMeshProUGUI TextMeshProUGUI_Device;
        private TextMeshProUGUI TextMeshProUGUI_Flight;
        private TextMeshProUGUI TextMeshProUGUI_Camera;
        private TextMeshProUGUI TextMeshProUGUI_Takeoff;
        private TextMeshProUGUI TextMeshProUGUI_Equipment;
        private TextMeshProUGUI TextMeshProUGUI_Reset;
        private TextMeshProUGUI TextMeshProUGUI_ReturnLabel;
        private Button Button_Close;
        private Button Button_Return;
        private UIMenuScope UIMenuScope_DroneFlightHelpView;
        private ScrollRect ScrollRect_Guide;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            TextMeshProUGUI_Device = componentItemIndex.Get<TextMeshProUGUI>(0);
            TextMeshProUGUI_Flight = componentItemIndex.Get<TextMeshProUGUI>(1);
            TextMeshProUGUI_Camera = componentItemIndex.Get<TextMeshProUGUI>(2);
            TextMeshProUGUI_Takeoff = componentItemIndex.Get<TextMeshProUGUI>(3);
            TextMeshProUGUI_Equipment = componentItemIndex.Get<TextMeshProUGUI>(4);
            TextMeshProUGUI_Reset = componentItemIndex.Get<TextMeshProUGUI>(5);
            TextMeshProUGUI_ReturnLabel = componentItemIndex.Get<TextMeshProUGUI>(6);
            Button_Close = componentItemIndex.Get<Button>(7);
            Button_Return = componentItemIndex.Get<Button>(8);
            UIMenuScope_DroneFlightHelpView = componentItemIndex.Get<UIMenuScope>(9);
            ScrollRect_Guide = componentItemIndex.Get<ScrollRect>(10);
        }
    }
}
