// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;

    [Source("LoadResources/Demos/block_porters/Prefabs/UI/BlockPortersSettingsView")]
    public partial class BlockPortersSettingsView
    {
        public override string Address => "LoadResources/Demos/block_porters/Prefabs/UI/BlockPortersSettingsView";
        public override UILayer Level => UILayer.Tip;
        public override UIViewMode ViewMode => UIViewMode.Modal;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private Button Button_SettingsClose;
        private Button Button_Sound;
        private TextMeshProUGUI TextMeshProUGUI_SoundLabel;
        private Button Button_Restart;
        private Button Button_Exit;
        private Button Button_SettingsContinue;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            Button_SettingsClose = componentItemIndex.Get<Button>(0);
            Button_Sound = componentItemIndex.Get<Button>(1);
            TextMeshProUGUI_SoundLabel = componentItemIndex.Get<TextMeshProUGUI>(2);
            Button_Restart = componentItemIndex.Get<Button>(3);
            Button_Exit = componentItemIndex.Get<Button>(4);
            Button_SettingsContinue = componentItemIndex.Get<Button>(5);
        }
    }
}
