// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.HowToFish;
    using TMPro;

    [Source("LoadResources/Demos/how_to_fish/Prefabs/UI/HowToFishHudView")]
    public partial class HowToFishHudView
    {
        public override string Address => "LoadResources/Demos/how_to_fish/Prefabs/UI/HowToFishHudView";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private HowToFishHudPresenter HowToFishHudPresenter_HowToFishHudView;
        private TextMeshProUGUI TextMeshProUGUI_Stats;
        private TextMeshProUGUI TextMeshProUGUI_Focus;
        private TextMeshProUGUI TextMeshProUGUI_Crosshair;
        private TextMeshProUGUI TextMeshProUGUI_Controls;
        private TextMeshProUGUI TextMeshProUGUI_FishingStatus;
        private Image Image_TensionTrack;
        private Image Image_Tension;
        private Image Image_Menu;
        private TextMeshProUGUI TextMeshProUGUI_MenuTitle;
        private Button Button_Slot0;
        private TextMeshProUGUI TextMeshProUGUI_Slot0Label;
        private Button Button_New0;
        private TextMeshProUGUI TextMeshProUGUI_New0Label;
        private Button Button_Slot1;
        private TextMeshProUGUI TextMeshProUGUI_Slot1Label;
        private Button Button_New1;
        private TextMeshProUGUI TextMeshProUGUI_New1Label;
        private Button Button_Slot2;
        private TextMeshProUGUI TextMeshProUGUI_Slot2Label;
        private Button Button_New2;
        private TextMeshProUGUI TextMeshProUGUI_New2Label;
        private Button Button_Resume;
        private TextMeshProUGUI TextMeshProUGUI_ResumeLabel;
        private Button Button_Save;
        private TextMeshProUGUI TextMeshProUGUI_SaveLabel;
        private Button Button_ReturnHub;
        private TextMeshProUGUI TextMeshProUGUI_ReturnHubLabel;
        private TextMeshProUGUI TextMeshProUGUI_Journal;
        private TextMeshProUGUI TextMeshProUGUI_Notice;
        private TextMeshProUGUI TextMeshProUGUI_BossStatus;
        private Image Image_BossHealthTrack;
        private Image Image_BossHealth;
        private Image Image_BossEscapeTrack;
        private Image Image_BossEscape;
        private Image Image_RadarPanel;
        private TextMeshProUGUI TextMeshProUGUI_RadarStatus;
        private Image Image_RadarAxisX;
        private Image Image_RadarAxisY;
        private TextMeshProUGUI TextMeshProUGUI_RadarPlayer;
        private TextMeshProUGUI TextMeshProUGUI_RadarIsland0;
        private TextMeshProUGUI TextMeshProUGUI_RadarIsland1;
        private TextMeshProUGUI TextMeshProUGUI_RadarIsland2;
        private TextMeshProUGUI TextMeshProUGUI_RadarIsland3;
        private TextMeshProUGUI TextMeshProUGUI_RadarIsland4;
        private TextMeshProUGUI TextMeshProUGUI_EquipmentSlots;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            HowToFishHudPresenter_HowToFishHudView = componentItemIndex.Get<HowToFishHudPresenter>(0);
            TextMeshProUGUI_Stats = componentItemIndex.Get<TextMeshProUGUI>(1);
            TextMeshProUGUI_Focus = componentItemIndex.Get<TextMeshProUGUI>(2);
            TextMeshProUGUI_Crosshair = componentItemIndex.Get<TextMeshProUGUI>(3);
            TextMeshProUGUI_Controls = componentItemIndex.Get<TextMeshProUGUI>(4);
            TextMeshProUGUI_FishingStatus = componentItemIndex.Get<TextMeshProUGUI>(5);
            Image_TensionTrack = componentItemIndex.Get<Image>(6);
            Image_Tension = componentItemIndex.Get<Image>(7);
            Image_Menu = componentItemIndex.Get<Image>(8);
            TextMeshProUGUI_MenuTitle = componentItemIndex.Get<TextMeshProUGUI>(9);
            Button_Slot0 = componentItemIndex.Get<Button>(10);
            TextMeshProUGUI_Slot0Label = componentItemIndex.Get<TextMeshProUGUI>(11);
            Button_New0 = componentItemIndex.Get<Button>(12);
            TextMeshProUGUI_New0Label = componentItemIndex.Get<TextMeshProUGUI>(13);
            Button_Slot1 = componentItemIndex.Get<Button>(14);
            TextMeshProUGUI_Slot1Label = componentItemIndex.Get<TextMeshProUGUI>(15);
            Button_New1 = componentItemIndex.Get<Button>(16);
            TextMeshProUGUI_New1Label = componentItemIndex.Get<TextMeshProUGUI>(17);
            Button_Slot2 = componentItemIndex.Get<Button>(18);
            TextMeshProUGUI_Slot2Label = componentItemIndex.Get<TextMeshProUGUI>(19);
            Button_New2 = componentItemIndex.Get<Button>(20);
            TextMeshProUGUI_New2Label = componentItemIndex.Get<TextMeshProUGUI>(21);
            Button_Resume = componentItemIndex.Get<Button>(22);
            TextMeshProUGUI_ResumeLabel = componentItemIndex.Get<TextMeshProUGUI>(23);
            Button_Save = componentItemIndex.Get<Button>(24);
            TextMeshProUGUI_SaveLabel = componentItemIndex.Get<TextMeshProUGUI>(25);
            Button_ReturnHub = componentItemIndex.Get<Button>(26);
            TextMeshProUGUI_ReturnHubLabel = componentItemIndex.Get<TextMeshProUGUI>(27);
            TextMeshProUGUI_Journal = componentItemIndex.Get<TextMeshProUGUI>(28);
            TextMeshProUGUI_Notice = componentItemIndex.Get<TextMeshProUGUI>(29);
            TextMeshProUGUI_BossStatus = componentItemIndex.Get<TextMeshProUGUI>(30);
            Image_BossHealthTrack = componentItemIndex.Get<Image>(31);
            Image_BossHealth = componentItemIndex.Get<Image>(32);
            Image_BossEscapeTrack = componentItemIndex.Get<Image>(33);
            Image_BossEscape = componentItemIndex.Get<Image>(34);
            Image_RadarPanel = componentItemIndex.Get<Image>(35);
            TextMeshProUGUI_RadarStatus = componentItemIndex.Get<TextMeshProUGUI>(36);
            Image_RadarAxisX = componentItemIndex.Get<Image>(37);
            Image_RadarAxisY = componentItemIndex.Get<Image>(38);
            TextMeshProUGUI_RadarPlayer = componentItemIndex.Get<TextMeshProUGUI>(39);
            TextMeshProUGUI_RadarIsland0 = componentItemIndex.Get<TextMeshProUGUI>(40);
            TextMeshProUGUI_RadarIsland1 = componentItemIndex.Get<TextMeshProUGUI>(41);
            TextMeshProUGUI_RadarIsland2 = componentItemIndex.Get<TextMeshProUGUI>(42);
            TextMeshProUGUI_RadarIsland3 = componentItemIndex.Get<TextMeshProUGUI>(43);
            TextMeshProUGUI_RadarIsland4 = componentItemIndex.Get<TextMeshProUGUI>(44);
            TextMeshProUGUI_EquipmentSlots = componentItemIndex.Get<TextMeshProUGUI>(45);
        }
    }
}
