// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.HowToFish;
    using TMPro;

    [Source("LoadResources/Demos/how_to_fish/Prefabs/UI/HowToFishHudView")]
    public partial class HowToFishHudView
    {
        public override string Address => "LoadResources/Demos/how_to_fish/Prefabs/UI/HowToFishHudView";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private TextMeshProUGUI TextMeshProUGUI_Stats;
        private TextMeshProUGUI TextMeshProUGUI_Focus;
        private TextMeshProUGUI TextMeshProUGUI_Controls;
        private HowToFishFishingHudPresenter HowToFishFishingHudPresenter_FishingPanel;
        private TextMeshProUGUI TextMeshProUGUI_Notice;
        private HowToFishBossHudPresenter HowToFishBossHudPresenter_BossPanel;
        private HowToFishRadarHudPresenter HowToFishRadarHudPresenter_RadarPanel;
        private TextMeshProUGUI TextMeshProUGUI_EquipmentSlots;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            TextMeshProUGUI_Stats = componentItemIndex.Get<TextMeshProUGUI>(0);
            TextMeshProUGUI_Focus = componentItemIndex.Get<TextMeshProUGUI>(1);
            TextMeshProUGUI_Controls = componentItemIndex.Get<TextMeshProUGUI>(2);
            HowToFishFishingHudPresenter_FishingPanel = componentItemIndex.Get<HowToFishFishingHudPresenter>(3);
            TextMeshProUGUI_Notice = componentItemIndex.Get<TextMeshProUGUI>(4);
            HowToFishBossHudPresenter_BossPanel = componentItemIndex.Get<HowToFishBossHudPresenter>(5);
            HowToFishRadarHudPresenter_RadarPanel = componentItemIndex.Get<HowToFishRadarHudPresenter>(6);
            TextMeshProUGUI_EquipmentSlots = componentItemIndex.Get<TextMeshProUGUI>(7);
        }
    }
}
