// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.HowToFish;
    using TMPro;

    [Source("LoadResources/Demos/how_to_fish/Prefabs/UI/HowToFishHudView")]
    public partial class HowToFishHudView
    {
        public override string Address => "LoadResources/Demos/how_to_fish/Prefabs/UI/HowToFishHudView";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private HowToFishHudPresenter HowToFishHudPresenter_HowToFishHudView;
        private TextMeshProUGUI TextMeshProUGUI_Stats;
        private TextMeshProUGUI TextMeshProUGUI_Focus;
        private TextMeshProUGUI TextMeshProUGUI_Crosshair;
        private TextMeshProUGUI TextMeshProUGUI_Controls;
        private TextMeshProUGUI TextMeshProUGUI_FishingStatus;
        private Image Image_TensionTrack;
        private Image Image_Tension;
        private Image Image_Menu;
        private TextMeshProUGUI TextMeshProUGUI_MenuTitle;
        private Button Button_Slot0;
        private TextMeshProUGUI TextMeshProUGUI_Slot0Label;
        private Button Button_New0;
        private TextMeshProUGUI TextMeshProUGUI_New0Label;
        private Button Button_Slot1;
        private TextMeshProUGUI TextMeshProUGUI_Slot1Label;
        private Button Button_New1;
        private TextMeshProUGUI TextMeshProUGUI_New1Label;
        private Button Button_Slot2;
        private TextMeshProUGUI TextMeshProUGUI_Slot2Label;
        private Button Button_New2;
        private TextMeshProUGUI TextMeshProUGUI_New2Label;
        private Button Button_Resume;
        private TextMeshProUGUI TextMeshProUGUI_ResumeLabel;
        private Button Button_Save;
        private TextMeshProUGUI TextMeshProUGUI_SaveLabel;
        private Button Button_ReturnHub;
        private TextMeshProUGUI TextMeshProUGUI_ReturnHubLabel;
        private TextMeshProUGUI TextMeshProUGUI_Journal;
        private Button Button_OpenOutfits;
        private TextMeshProUGUI TextMeshProUGUI_OpenOutfitsLabel;
        private TextMeshProUGUI TextMeshProUGUI_Notice;
        private TextMeshProUGUI TextMeshProUGUI_BossStatus;
        private Image Image_BossHealthTrack;
        private Image Image_BossHealth;
        private Image Image_BossEscapeTrack;
        private Image Image_BossEscape;
        private Image Image_RadarPanel;
        private TextMeshProUGUI TextMeshProUGUI_RadarStatus;
        private Image Image_RadarAxisX;
        private Image Image_RadarAxisY;
        private TextMeshProUGUI TextMeshProUGUI_RadarPlayer;
        private TextMeshProUGUI TextMeshProUGUI_RadarIsland0;
        private TextMeshProUGUI TextMeshProUGUI_RadarIsland1;
        private TextMeshProUGUI TextMeshProUGUI_RadarIsland2;
        private TextMeshProUGUI TextMeshProUGUI_RadarIsland3;
        private TextMeshProUGUI TextMeshProUGUI_RadarIsland4;
        private TextMeshProUGUI TextMeshProUGUI_EquipmentSlots;
        private Image Image_OutfitPanel;
        private TextMeshProUGUI TextMeshProUGUI_OutfitTitle;
        private Button Button_OutfitBadman;
        private TextMeshProUGUI TextMeshProUGUI_OutfitBadmanLabel;
        private Image Image_Icon;
        private Button Button_OutfitBikini;
        private TextMeshProUGUI TextMeshProUGUI_OutfitBikiniLabel;
        private Image Image_Icon1;
        private Button Button_OutfitFisherman;
        private TextMeshProUGUI TextMeshProUGUI_OutfitFishermanLabel;
        private Image Image_Icon2;
        private Button Button_OutfitSailor;
        private TextMeshProUGUI TextMeshProUGUI_OutfitSailorLabel;
        private Image Image_Icon3;
        private Button Button_OutfitLighthouseKeeper;
        private TextMeshProUGUI TextMeshProUGUI_OutfitLighthouseKeeperLabel;
        private Image Image_Icon4;
        private Button Button_OutfitSwampMan;
        private TextMeshProUGUI TextMeshProUGUI_OutfitSwampManLabel;
        private Image Image_Icon5;
        private Button Button_OutfitSwampLady;
        private TextMeshProUGUI TextMeshProUGUI_OutfitSwampLadyLabel;
        private Image Image_Icon6;
        private Button Button_OutfitKioskLady;
        private TextMeshProUGUI TextMeshProUGUI_OutfitKioskLadyLabel;
        private Image Image_Icon7;
        private Button Button_OutfitTourist;
        private TextMeshProUGUI TextMeshProUGUI_OutfitTouristLabel;
        private Image Image_Icon8;
        private Button Button_OutfitGrillMaster;
        private TextMeshProUGUI TextMeshProUGUI_OutfitGrillMasterLabel;
        private Image Image_Icon9;
        private Button Button_OutfitAndrei;
        private TextMeshProUGUI TextMeshProUGUI_OutfitAndreiLabel;
        private Image Image_Icon10;
        private Button Button_OutfitJacob;
        private TextMeshProUGUI TextMeshProUGUI_OutfitJacobLabel;
        private Image Image_Icon11;
        private Button Button_OutfitGunstoreClerc;
        private TextMeshProUGUI TextMeshProUGUI_OutfitGunstoreClercLabel;
        private Image Image_Icon12;
        private Button Button_OutfitScaredGuyInShorts;
        private TextMeshProUGUI TextMeshProUGUI_OutfitScaredGuyInShortsLabel;
        private Image Image_Icon13;
        private Button Button_OutfitStoreGrandma;
        private TextMeshProUGUI TextMeshProUGUI_OutfitStoreGrandmaLabel;
        private Image Image_Icon14;
        private Button Button_OutfitMilitary;
        private TextMeshProUGUI TextMeshProUGUI_OutfitMilitaryLabel;
        private Image Image_Icon15;
        private Button Button_OutfitScientist;
        private TextMeshProUGUI TextMeshProUGUI_OutfitScientistLabel;
        private Image Image_Icon16;
        private Button Button_OutfitBean;
        private TextMeshProUGUI TextMeshProUGUI_OutfitBeanLabel;
        private Image Image_Icon17;
        private TextMeshProUGUI TextMeshProUGUI_OutfitDetails;
        private Button Button_WearOutfit;
        private TextMeshProUGUI TextMeshProUGUI_WearOutfitLabel;
        private Button Button_CloseOutfits;
        private TextMeshProUGUI TextMeshProUGUI_CloseOutfitsLabel;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            HowToFishHudPresenter_HowToFishHudView = componentItemIndex.Get<HowToFishHudPresenter>(0);
            TextMeshProUGUI_Stats = componentItemIndex.Get<TextMeshProUGUI>(1);
            TextMeshProUGUI_Focus = componentItemIndex.Get<TextMeshProUGUI>(2);
            TextMeshProUGUI_Crosshair = componentItemIndex.Get<TextMeshProUGUI>(3);
            TextMeshProUGUI_Controls = componentItemIndex.Get<TextMeshProUGUI>(4);
            TextMeshProUGUI_FishingStatus = componentItemIndex.Get<TextMeshProUGUI>(5);
            Image_TensionTrack = componentItemIndex.Get<Image>(6);
            Image_Tension = componentItemIndex.Get<Image>(7);
            Image_Menu = componentItemIndex.Get<Image>(8);
            TextMeshProUGUI_MenuTitle = componentItemIndex.Get<TextMeshProUGUI>(9);
            Button_Slot0 = componentItemIndex.Get<Button>(10);
            TextMeshProUGUI_Slot0Label = componentItemIndex.Get<TextMeshProUGUI>(11);
            Button_New0 = componentItemIndex.Get<Button>(12);
            TextMeshProUGUI_New0Label = componentItemIndex.Get<TextMeshProUGUI>(13);
            Button_Slot1 = componentItemIndex.Get<Button>(14);
            TextMeshProUGUI_Slot1Label = componentItemIndex.Get<TextMeshProUGUI>(15);
            Button_New1 = componentItemIndex.Get<Button>(16);
            TextMeshProUGUI_New1Label = componentItemIndex.Get<TextMeshProUGUI>(17);
            Button_Slot2 = componentItemIndex.Get<Button>(18);
            TextMeshProUGUI_Slot2Label = componentItemIndex.Get<TextMeshProUGUI>(19);
            Button_New2 = componentItemIndex.Get<Button>(20);
            TextMeshProUGUI_New2Label = componentItemIndex.Get<TextMeshProUGUI>(21);
            Button_Resume = componentItemIndex.Get<Button>(22);
            TextMeshProUGUI_ResumeLabel = componentItemIndex.Get<TextMeshProUGUI>(23);
            Button_Save = componentItemIndex.Get<Button>(24);
            TextMeshProUGUI_SaveLabel = componentItemIndex.Get<TextMeshProUGUI>(25);
            Button_ReturnHub = componentItemIndex.Get<Button>(26);
            TextMeshProUGUI_ReturnHubLabel = componentItemIndex.Get<TextMeshProUGUI>(27);
            TextMeshProUGUI_Journal = componentItemIndex.Get<TextMeshProUGUI>(28);
            Button_OpenOutfits = componentItemIndex.Get<Button>(29);
            TextMeshProUGUI_OpenOutfitsLabel = componentItemIndex.Get<TextMeshProUGUI>(30);
            TextMeshProUGUI_Notice = componentItemIndex.Get<TextMeshProUGUI>(31);
            TextMeshProUGUI_BossStatus = componentItemIndex.Get<TextMeshProUGUI>(32);
            Image_BossHealthTrack = componentItemIndex.Get<Image>(33);
            Image_BossHealth = componentItemIndex.Get<Image>(34);
            Image_BossEscapeTrack = componentItemIndex.Get<Image>(35);
            Image_BossEscape = componentItemIndex.Get<Image>(36);
            Image_RadarPanel = componentItemIndex.Get<Image>(37);
            TextMeshProUGUI_RadarStatus = componentItemIndex.Get<TextMeshProUGUI>(38);
            Image_RadarAxisX = componentItemIndex.Get<Image>(39);
            Image_RadarAxisY = componentItemIndex.Get<Image>(40);
            TextMeshProUGUI_RadarPlayer = componentItemIndex.Get<TextMeshProUGUI>(41);
            TextMeshProUGUI_RadarIsland0 = componentItemIndex.Get<TextMeshProUGUI>(42);
            TextMeshProUGUI_RadarIsland1 = componentItemIndex.Get<TextMeshProUGUI>(43);
            TextMeshProUGUI_RadarIsland2 = componentItemIndex.Get<TextMeshProUGUI>(44);
            TextMeshProUGUI_RadarIsland3 = componentItemIndex.Get<TextMeshProUGUI>(45);
            TextMeshProUGUI_RadarIsland4 = componentItemIndex.Get<TextMeshProUGUI>(46);
            TextMeshProUGUI_EquipmentSlots = componentItemIndex.Get<TextMeshProUGUI>(47);
            Image_OutfitPanel = componentItemIndex.Get<Image>(48);
            TextMeshProUGUI_OutfitTitle = componentItemIndex.Get<TextMeshProUGUI>(49);
            Button_OutfitBadman = componentItemIndex.Get<Button>(50);
            TextMeshProUGUI_OutfitBadmanLabel = componentItemIndex.Get<TextMeshProUGUI>(51);
            Image_Icon = componentItemIndex.Get<Image>(52);
            Button_OutfitBikini = componentItemIndex.Get<Button>(53);
            TextMeshProUGUI_OutfitBikiniLabel = componentItemIndex.Get<TextMeshProUGUI>(54);
            Image_Icon1 = componentItemIndex.Get<Image>(55);
            Button_OutfitFisherman = componentItemIndex.Get<Button>(56);
            TextMeshProUGUI_OutfitFishermanLabel = componentItemIndex.Get<TextMeshProUGUI>(57);
            Image_Icon2 = componentItemIndex.Get<Image>(58);
            Button_OutfitSailor = componentItemIndex.Get<Button>(59);
            TextMeshProUGUI_OutfitSailorLabel = componentItemIndex.Get<TextMeshProUGUI>(60);
            Image_Icon3 = componentItemIndex.Get<Image>(61);
            Button_OutfitLighthouseKeeper = componentItemIndex.Get<Button>(62);
            TextMeshProUGUI_OutfitLighthouseKeeperLabel = componentItemIndex.Get<TextMeshProUGUI>(63);
            Image_Icon4 = componentItemIndex.Get<Image>(64);
            Button_OutfitSwampMan = componentItemIndex.Get<Button>(65);
            TextMeshProUGUI_OutfitSwampManLabel = componentItemIndex.Get<TextMeshProUGUI>(66);
            Image_Icon5 = componentItemIndex.Get<Image>(67);
            Button_OutfitSwampLady = componentItemIndex.Get<Button>(68);
            TextMeshProUGUI_OutfitSwampLadyLabel = componentItemIndex.Get<TextMeshProUGUI>(69);
            Image_Icon6 = componentItemIndex.Get<Image>(70);
            Button_OutfitKioskLady = componentItemIndex.Get<Button>(71);
            TextMeshProUGUI_OutfitKioskLadyLabel = componentItemIndex.Get<TextMeshProUGUI>(72);
            Image_Icon7 = componentItemIndex.Get<Image>(73);
            Button_OutfitTourist = componentItemIndex.Get<Button>(74);
            TextMeshProUGUI_OutfitTouristLabel = componentItemIndex.Get<TextMeshProUGUI>(75);
            Image_Icon8 = componentItemIndex.Get<Image>(76);
            Button_OutfitGrillMaster = componentItemIndex.Get<Button>(77);
            TextMeshProUGUI_OutfitGrillMasterLabel = componentItemIndex.Get<TextMeshProUGUI>(78);
            Image_Icon9 = componentItemIndex.Get<Image>(79);
            Button_OutfitAndrei = componentItemIndex.Get<Button>(80);
            TextMeshProUGUI_OutfitAndreiLabel = componentItemIndex.Get<TextMeshProUGUI>(81);
            Image_Icon10 = componentItemIndex.Get<Image>(82);
            Button_OutfitJacob = componentItemIndex.Get<Button>(83);
            TextMeshProUGUI_OutfitJacobLabel = componentItemIndex.Get<TextMeshProUGUI>(84);
            Image_Icon11 = componentItemIndex.Get<Image>(85);
            Button_OutfitGunstoreClerc = componentItemIndex.Get<Button>(86);
            TextMeshProUGUI_OutfitGunstoreClercLabel = componentItemIndex.Get<TextMeshProUGUI>(87);
            Image_Icon12 = componentItemIndex.Get<Image>(88);
            Button_OutfitScaredGuyInShorts = componentItemIndex.Get<Button>(89);
            TextMeshProUGUI_OutfitScaredGuyInShortsLabel = componentItemIndex.Get<TextMeshProUGUI>(90);
            Image_Icon13 = componentItemIndex.Get<Image>(91);
            Button_OutfitStoreGrandma = componentItemIndex.Get<Button>(92);
            TextMeshProUGUI_OutfitStoreGrandmaLabel = componentItemIndex.Get<TextMeshProUGUI>(93);
            Image_Icon14 = componentItemIndex.Get<Image>(94);
            Button_OutfitMilitary = componentItemIndex.Get<Button>(95);
            TextMeshProUGUI_OutfitMilitaryLabel = componentItemIndex.Get<TextMeshProUGUI>(96);
            Image_Icon15 = componentItemIndex.Get<Image>(97);
            Button_OutfitScientist = componentItemIndex.Get<Button>(98);
            TextMeshProUGUI_OutfitScientistLabel = componentItemIndex.Get<TextMeshProUGUI>(99);
            Image_Icon16 = componentItemIndex.Get<Image>(100);
            Button_OutfitBean = componentItemIndex.Get<Button>(101);
            TextMeshProUGUI_OutfitBeanLabel = componentItemIndex.Get<TextMeshProUGUI>(102);
            Image_Icon17 = componentItemIndex.Get<Image>(103);
            TextMeshProUGUI_OutfitDetails = componentItemIndex.Get<TextMeshProUGUI>(104);
            Button_WearOutfit = componentItemIndex.Get<Button>(105);
            TextMeshProUGUI_WearOutfitLabel = componentItemIndex.Get<TextMeshProUGUI>(106);
            Button_CloseOutfits = componentItemIndex.Get<Button>(107);
            TextMeshProUGUI_CloseOutfitsLabel = componentItemIndex.Get<TextMeshProUGUI>(108);
        }
    }
}
