// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.BlockPorters.Adapters;
    using TMPro;

    [Source("LoadResources/Demos/block_porters/Prefabs/UI/BlockPortersHudView")]
    public partial class BlockPortersHudView
    {
        public override string Address => "LoadResources/Demos/block_porters/Prefabs/UI/BlockPortersHudView";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private BlockPortersHudPresenter BlockPortersHudPresenter_BlockPortersHudView;
        private TextMeshProUGUI TextMeshProUGUI_Title;
        private TextMeshProUGUI TextMeshProUGUI_Subtitle;
        private Button Button_Exit;
        private TextMeshProUGUI TextMeshProUGUI_ExitLabel;
        private Image Image_ProgressTrack;
        private Image Image_ProgressFill;
        private TextMeshProUGUI TextMeshProUGUI_Progress;
        private TextMeshProUGUI TextMeshProUGUI_SlotsTitle;
        private Image Image_TaskSlot0;
        private TextMeshProUGUI TextMeshProUGUI_TaskLabel0;
        private Image Image_TaskSlot1;
        private TextMeshProUGUI TextMeshProUGUI_TaskLabel1;
        private Image Image_TaskSlot2;
        private TextMeshProUGUI TextMeshProUGUI_TaskLabel2;
        private Image Image_TaskSlot3;
        private TextMeshProUGUI TextMeshProUGUI_TaskLabel3;
        private Image Image_TaskSlot4;
        private TextMeshProUGUI TextMeshProUGUI_TaskLabel4;
        private Image Image_TaskSlot5;
        private TextMeshProUGUI TextMeshProUGUI_TaskLabel5;
        private Image Image_TaskSlot6;
        private TextMeshProUGUI TextMeshProUGUI_TaskLabel6;
        private TextMeshProUGUI TextMeshProUGUI_Hint;
        private Button Button_Queue0;
        private TextMeshProUGUI TextMeshProUGUI_Queue0Label;
        private Image Image_Preview0;
        private TextMeshProUGUI TextMeshProUGUI_PreviewLabel0;
        private Button Button_Queue1;
        private TextMeshProUGUI TextMeshProUGUI_Queue1Label;
        private Image Image_Preview2;
        private TextMeshProUGUI TextMeshProUGUI_PreviewLabel2;
        private Button Button_Queue2;
        private TextMeshProUGUI TextMeshProUGUI_Queue2Label;
        private Image Image_Preview4;
        private TextMeshProUGUI TextMeshProUGUI_PreviewLabel4;
        private Button Button_Queue3;
        private TextMeshProUGUI TextMeshProUGUI_Queue3Label;
        private Image Image_Preview6;
        private TextMeshProUGUI TextMeshProUGUI_PreviewLabel6;
        private Button Button_Pause;
        private TextMeshProUGUI TextMeshProUGUI_PauseLabel;
        private Button Button_Sound;
        private TextMeshProUGUI TextMeshProUGUI_SoundLabel;
        private Button Button_Restart;
        private TextMeshProUGUI TextMeshProUGUI_RestartLabel;
        private Image Image_ResultPanel;
        private TextMeshProUGUI TextMeshProUGUI_ResultTitle;
        private TextMeshProUGUI TextMeshProUGUI_ResultDescription;
        private Button Button_Revive;
        private TextMeshProUGUI TextMeshProUGUI_ReviveLabel;
        private Button Button_Next;
        private TextMeshProUGUI TextMeshProUGUI_NextLabel;
        private Button Button_ResultRestart;
        private TextMeshProUGUI TextMeshProUGUI_ResultRestartLabel;
        private Button Button_ResultExit;
        private TextMeshProUGUI TextMeshProUGUI_ResultExitLabel;
        private TextMeshProUGUI TextMeshProUGUI_SimulationNote;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            BlockPortersHudPresenter_BlockPortersHudView = componentItemIndex.Get<BlockPortersHudPresenter>(0);
            TextMeshProUGUI_Title = componentItemIndex.Get<TextMeshProUGUI>(1);
            TextMeshProUGUI_Subtitle = componentItemIndex.Get<TextMeshProUGUI>(2);
            Button_Exit = componentItemIndex.Get<Button>(3);
            TextMeshProUGUI_ExitLabel = componentItemIndex.Get<TextMeshProUGUI>(4);
            Image_ProgressTrack = componentItemIndex.Get<Image>(5);
            Image_ProgressFill = componentItemIndex.Get<Image>(6);
            TextMeshProUGUI_Progress = componentItemIndex.Get<TextMeshProUGUI>(7);
            TextMeshProUGUI_SlotsTitle = componentItemIndex.Get<TextMeshProUGUI>(8);
            Image_TaskSlot0 = componentItemIndex.Get<Image>(9);
            TextMeshProUGUI_TaskLabel0 = componentItemIndex.Get<TextMeshProUGUI>(10);
            Image_TaskSlot1 = componentItemIndex.Get<Image>(11);
            TextMeshProUGUI_TaskLabel1 = componentItemIndex.Get<TextMeshProUGUI>(12);
            Image_TaskSlot2 = componentItemIndex.Get<Image>(13);
            TextMeshProUGUI_TaskLabel2 = componentItemIndex.Get<TextMeshProUGUI>(14);
            Image_TaskSlot3 = componentItemIndex.Get<Image>(15);
            TextMeshProUGUI_TaskLabel3 = componentItemIndex.Get<TextMeshProUGUI>(16);
            Image_TaskSlot4 = componentItemIndex.Get<Image>(17);
            TextMeshProUGUI_TaskLabel4 = componentItemIndex.Get<TextMeshProUGUI>(18);
            Image_TaskSlot5 = componentItemIndex.Get<Image>(19);
            TextMeshProUGUI_TaskLabel5 = componentItemIndex.Get<TextMeshProUGUI>(20);
            Image_TaskSlot6 = componentItemIndex.Get<Image>(21);
            TextMeshProUGUI_TaskLabel6 = componentItemIndex.Get<TextMeshProUGUI>(22);
            TextMeshProUGUI_Hint = componentItemIndex.Get<TextMeshProUGUI>(23);
            Button_Queue0 = componentItemIndex.Get<Button>(24);
            TextMeshProUGUI_Queue0Label = componentItemIndex.Get<TextMeshProUGUI>(25);
            Image_Preview0 = componentItemIndex.Get<Image>(26);
            TextMeshProUGUI_PreviewLabel0 = componentItemIndex.Get<TextMeshProUGUI>(27);
            Button_Queue1 = componentItemIndex.Get<Button>(28);
            TextMeshProUGUI_Queue1Label = componentItemIndex.Get<TextMeshProUGUI>(29);
            Image_Preview2 = componentItemIndex.Get<Image>(30);
            TextMeshProUGUI_PreviewLabel2 = componentItemIndex.Get<TextMeshProUGUI>(31);
            Button_Queue2 = componentItemIndex.Get<Button>(32);
            TextMeshProUGUI_Queue2Label = componentItemIndex.Get<TextMeshProUGUI>(33);
            Image_Preview4 = componentItemIndex.Get<Image>(34);
            TextMeshProUGUI_PreviewLabel4 = componentItemIndex.Get<TextMeshProUGUI>(35);
            Button_Queue3 = componentItemIndex.Get<Button>(36);
            TextMeshProUGUI_Queue3Label = componentItemIndex.Get<TextMeshProUGUI>(37);
            Image_Preview6 = componentItemIndex.Get<Image>(38);
            TextMeshProUGUI_PreviewLabel6 = componentItemIndex.Get<TextMeshProUGUI>(39);
            Button_Pause = componentItemIndex.Get<Button>(40);
            TextMeshProUGUI_PauseLabel = componentItemIndex.Get<TextMeshProUGUI>(41);
            Button_Sound = componentItemIndex.Get<Button>(42);
            TextMeshProUGUI_SoundLabel = componentItemIndex.Get<TextMeshProUGUI>(43);
            Button_Restart = componentItemIndex.Get<Button>(44);
            TextMeshProUGUI_RestartLabel = componentItemIndex.Get<TextMeshProUGUI>(45);
            Image_ResultPanel = componentItemIndex.Get<Image>(46);
            TextMeshProUGUI_ResultTitle = componentItemIndex.Get<TextMeshProUGUI>(47);
            TextMeshProUGUI_ResultDescription = componentItemIndex.Get<TextMeshProUGUI>(48);
            Button_Revive = componentItemIndex.Get<Button>(49);
            TextMeshProUGUI_ReviveLabel = componentItemIndex.Get<TextMeshProUGUI>(50);
            Button_Next = componentItemIndex.Get<Button>(51);
            TextMeshProUGUI_NextLabel = componentItemIndex.Get<TextMeshProUGUI>(52);
            Button_ResultRestart = componentItemIndex.Get<Button>(53);
            TextMeshProUGUI_ResultRestartLabel = componentItemIndex.Get<TextMeshProUGUI>(54);
            Button_ResultExit = componentItemIndex.Get<Button>(55);
            TextMeshProUGUI_ResultExitLabel = componentItemIndex.Get<TextMeshProUGUI>(56);
            TextMeshProUGUI_SimulationNote = componentItemIndex.Get<TextMeshProUGUI>(57);
        }
    }
}
