// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;

    [Source("LoadResources/UI/Views/MainMenuView")]
    public partial class MainMenuView
    {
        public override string Address => "LoadResources/UI/Views/MainMenuView";
        public override UILayer Level => UILayer.Base;
        public override MaskType Mask => MaskType.None;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;

        private Image Image_Background;
        private TextMeshProUGUI TextMeshProUGUI_Title;
        private Button Button_UIFrameworkValidationButton;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            Image_Background = componentItemIndex.Get<Image>(0);
            TextMeshProUGUI_Title = componentItemIndex.Get<TextMeshProUGUI>(1);
            Button_UIFrameworkValidationButton = componentItemIndex.Get<Button>(2);
            this.RegisterButton(Button_UIFrameworkValidationButton, OnUIFrameworkValidationButtonClick);
        }
    }
}
