// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using SleepyStudios.LoopScroll;
    using TMPro;

    [Source("LoadResources/UI/Hall/MainMenuView")]
    public partial class MainMenuView
    {
        public override string Address => "LoadResources/UI/Hall/MainMenuView";
        public override UILayer Level => UILayer.Base;
        public override UIViewMode ViewMode => UIViewMode.Page;
        public override MaskType Mask => MaskType.None;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;

        private Image Image_Background;
        private TextMeshProUGUI TextMeshProUGUI_Title;
        private LoopScrollView LoopScrollView_DemoList;
        private TextMeshProUGUI TextMeshProUGUI_Status;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            Image_Background = componentItemIndex.Get<Image>(0);
            TextMeshProUGUI_Title = componentItemIndex.Get<TextMeshProUGUI>(1);
            LoopScrollView_DemoList = componentItemIndex.Get<LoopScrollView>(2);
            TextMeshProUGUI_Status = componentItemIndex.Get<TextMeshProUGUI>(3);
        }
    }
}
