// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using SleepyStudios.LoopScroll;
    using TMPro;

    [Source("LoadResources/UI/Hall/MainMenuView")]
    public partial class MainMenuView
    {
        public override string Address => "LoadResources/UI/Hall/MainMenuView";
        public override UILayer Level => UILayer.Base;
        public override UIViewMode ViewMode => UIViewMode.Page;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;

        private Image Image_Background;
        private TextMeshProUGUI TextMeshProUGUI_Title;
        private LoopScrollView LoopScrollView_DemoList;
        private TextMeshProUGUI TextMeshProUGUI_Status;
        private UIImageLoader UIImageLoader_Hero;
        private TextMeshProUGUI TextMeshProUGUI_Subtitle;
        private TextMeshProUGUI TextMeshProUGUI_Description;
        private Button Button_Start;
        private Button Button_Settings;
        private TextMeshProUGUI TextMeshProUGUI_StartLabel;
        private TextMeshProUGUI TextMeshProUGUI_Hints;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            Image_Background = componentItemIndex.Get<Image>(0);
            TextMeshProUGUI_Title = componentItemIndex.Get<TextMeshProUGUI>(1);
            LoopScrollView_DemoList = componentItemIndex.Get<LoopScrollView>(2);
            TextMeshProUGUI_Status = componentItemIndex.Get<TextMeshProUGUI>(3);
            UIImageLoader_Hero = componentItemIndex.Get<UIImageLoader>(4);
            TextMeshProUGUI_Subtitle = componentItemIndex.Get<TextMeshProUGUI>(5);
            TextMeshProUGUI_Description = componentItemIndex.Get<TextMeshProUGUI>(6);
            Button_Start = componentItemIndex.Get<Button>(7);
            Button_Settings = componentItemIndex.Get<Button>(8);
            TextMeshProUGUI_StartLabel = componentItemIndex.Get<TextMeshProUGUI>(9);
            TextMeshProUGUI_Hints = componentItemIndex.Get<TextMeshProUGUI>(10);
            this.RegisterButton(Button_Start, OnStartClick);
            this.RegisterButton(Button_Settings, OnSettingsClick);
        }
    }
}
