// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.DroneFlight;

    [Source("LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightHudView")]
    public partial class DroneFlightHudView
    {
        public override string Address => "LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightHudView";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private DroneHudPresenter DroneHudPresenter_DroneFlightHudView;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            DroneHudPresenter_DroneFlightHudView = componentItemIndex.Get<DroneHudPresenter>(0);
        }
    }
}
