// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Core.Runtime.Inputs;

    [Source("LoadResources/Demos/dlss/Prefabs/UI/DlssControls")]
    public partial class DlssControlsView
    {
        public override string Address => "LoadResources/Demos/dlss/Prefabs/UI/DlssControls";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => false;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private RectTransform RectTransform_TouchControls;
        private TouchInputPad TouchInputPad_Move;
        private TouchInputPad TouchInputPad_Look;
        private InputCommandButton InputCommandButton_Sprint;
        private InputBindingPrompt InputBindingPrompt_Prompt_按住加速;
        private InputCommandButton InputCommandButton_Reset;
        private InputBindingPrompt InputBindingPrompt_Prompt_重置视角;
        private InputCommandButton InputCommandButton_Settings;
        private InputBindingPrompt InputBindingPrompt_Prompt_画质设置;
        private InputCommandButton InputCommandButton_Exit;
        private InputBindingPrompt InputBindingPrompt_Prompt_返回_Hub;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            RectTransform_TouchControls = componentItemIndex.Get<RectTransform>(0);
            TouchInputPad_Move = componentItemIndex.Get<TouchInputPad>(1);
            TouchInputPad_Look = componentItemIndex.Get<TouchInputPad>(2);
            InputCommandButton_Sprint = componentItemIndex.Get<InputCommandButton>(3);
            InputBindingPrompt_Prompt_按住加速 = componentItemIndex.Get<InputBindingPrompt>(4);
            InputCommandButton_Reset = componentItemIndex.Get<InputCommandButton>(5);
            InputBindingPrompt_Prompt_重置视角 = componentItemIndex.Get<InputBindingPrompt>(6);
            InputCommandButton_Settings = componentItemIndex.Get<InputCommandButton>(7);
            InputBindingPrompt_Prompt_画质设置 = componentItemIndex.Get<InputBindingPrompt>(8);
            InputCommandButton_Exit = componentItemIndex.Get<InputCommandButton>(9);
            InputBindingPrompt_Prompt_返回_Hub = componentItemIndex.Get<InputBindingPrompt>(10);
        }
    }
}
