// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;

    [Source("LoadResources/UI/Common/CommonLoading")]
    public partial class CommonLoadingView
    {
        public override string Address => "LoadResources/UI/Common/CommonLoading";
        public override UILayer Level => UILayer.Base;
        public override UIViewMode ViewMode => UIViewMode.Page;
        public override MaskType Mask => MaskType.None;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;

        private Image Image_Background;
        private TextMeshProUGUI TextMeshProUGUI_Title;
        private TextMeshProUGUI TextMeshProUGUI_Description;
        private TextMeshProUGUI TextMeshProUGUI_Step;
        private TextMeshProUGUI TextMeshProUGUI_ProgressText;
        private TextMeshProUGUI TextMeshProUGUI_SizeText;
        private Image Image_ProgressFill;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            Image_Background = componentItemIndex.Get<Image>(0);
            TextMeshProUGUI_Title = componentItemIndex.Get<TextMeshProUGUI>(1);
            TextMeshProUGUI_Description = componentItemIndex.Get<TextMeshProUGUI>(2);
            TextMeshProUGUI_Step = componentItemIndex.Get<TextMeshProUGUI>(3);
            TextMeshProUGUI_ProgressText = componentItemIndex.Get<TextMeshProUGUI>(4);
            TextMeshProUGUI_SizeText = componentItemIndex.Get<TextMeshProUGUI>(5);
            Image_ProgressFill = componentItemIndex.Get<Image>(6);
        }
    }
}
