// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;

    [Source("LoadResources/UI/Hall/MainMenuDemoItemView")]
    public partial class MainMenuDemoItemView
    {

        private UIImageLoader UIImageLoader_Preview;
        private TextMeshProUGUI TextMeshProUGUI_Title;
        private TextMeshProUGUI TextMeshProUGUI_Description;
        private LoopScrollMenuButton LoopScrollMenuButton_Enter;
        private TextMeshProUGUI TextMeshProUGUI_Action;
        private Image Image_Selection;
        private Image Image_Badge;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            UIImageLoader_Preview = componentItemIndex.Get<UIImageLoader>(0);
            TextMeshProUGUI_Title = componentItemIndex.Get<TextMeshProUGUI>(1);
            TextMeshProUGUI_Description = componentItemIndex.Get<TextMeshProUGUI>(2);
            LoopScrollMenuButton_Enter = componentItemIndex.Get<LoopScrollMenuButton>(3);
            TextMeshProUGUI_Action = componentItemIndex.Get<TextMeshProUGUI>(4);
            Image_Selection = componentItemIndex.Get<Image>(5);
            Image_Badge = componentItemIndex.Get<Image>(6);
            this.RegisterButton(LoopScrollMenuButton_Enter, OnEnterClick);
        }
    }
}
