// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;

    [Source("LoadResources/UI/GraphicsSettings/DlssSettingsView")]
    public partial class DlssSettingsView
    {
        public override string Address => "LoadResources/UI/GraphicsSettings/DlssSettingsView";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private TextMeshProUGUI TextMeshProUGUI_DeviceText;
        private TextMeshProUGUI TextMeshProUGUI_ModeText;
        private Button Button_OffButton;
        private Button Button_QualityButton;
        private Button Button_BalancedButton;
        private Button Button_PerformanceButton;
        private Button Button_UltraPerformanceButton;
        private Button Button_DlaaButton;
        private TextMeshProUGUI TextMeshProUGUI_ResolutionText;
        private TextMeshProUGUI TextMeshProUGUI_StatusText;
        private Button Button_CloseButton;
        private Button Button_OpenButton;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            TextMeshProUGUI_DeviceText = componentItemIndex.Get<TextMeshProUGUI>(0);
            TextMeshProUGUI_ModeText = componentItemIndex.Get<TextMeshProUGUI>(1);
            Button_OffButton = componentItemIndex.Get<Button>(2);
            Button_QualityButton = componentItemIndex.Get<Button>(3);
            Button_BalancedButton = componentItemIndex.Get<Button>(4);
            Button_PerformanceButton = componentItemIndex.Get<Button>(5);
            Button_UltraPerformanceButton = componentItemIndex.Get<Button>(6);
            Button_DlaaButton = componentItemIndex.Get<Button>(7);
            TextMeshProUGUI_ResolutionText = componentItemIndex.Get<TextMeshProUGUI>(8);
            TextMeshProUGUI_StatusText = componentItemIndex.Get<TextMeshProUGUI>(9);
            Button_CloseButton = componentItemIndex.Get<Button>(10);
            Button_OpenButton = componentItemIndex.Get<Button>(11);
            this.RegisterButton(Button_OffButton, OnOffButtonClick);
            this.RegisterButton(Button_QualityButton, OnQualityButtonClick);
            this.RegisterButton(Button_BalancedButton, OnBalancedButtonClick);
            this.RegisterButton(Button_PerformanceButton, OnPerformanceButtonClick);
            this.RegisterButton(Button_UltraPerformanceButton, OnUltraPerformanceButtonClick);
            this.RegisterButton(Button_DlaaButton, OnDlaaButtonClick);
            this.RegisterButton(Button_CloseButton, OnCloseButtonClick);
            this.RegisterButton(Button_OpenButton, OnOpenButtonClick);
        }
    }
}
