// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Core.Runtime.Inputs;
    using TMPro;

    [Source("LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightDebugView")]
    public partial class DroneFlightDebugView
    {
        public override string Address => "LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightDebugView";
        public override UILayer Level => UILayer.Tip;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private TextMeshProUGUI TextMeshProUGUI_FrontLeft;
        private TextMeshProUGUI TextMeshProUGUI_FrontRight;
        private TextMeshProUGUI TextMeshProUGUI_RearLeft;
        private TextMeshProUGUI TextMeshProUGUI_RearRight;
        private TextMeshProUGUI TextMeshProUGUI_Thrust;
        private TextMeshProUGUI TextMeshProUGUI_Pid;
        private TextMeshProUGUI TextMeshProUGUI_Mass;
        private TextMeshProUGUI TextMeshProUGUI_Equipment;
        private Button Button_Close;
        private Button Button_Vectors;
        private Button Button_Copy;
        private ScrollRect ScrollRect_Readout;
        private UIMenuScope UIMenuScope_DroneFlightDebugView;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            TextMeshProUGUI_FrontLeft = componentItemIndex.Get<TextMeshProUGUI>(0);
            TextMeshProUGUI_FrontRight = componentItemIndex.Get<TextMeshProUGUI>(1);
            TextMeshProUGUI_RearLeft = componentItemIndex.Get<TextMeshProUGUI>(2);
            TextMeshProUGUI_RearRight = componentItemIndex.Get<TextMeshProUGUI>(3);
            TextMeshProUGUI_Thrust = componentItemIndex.Get<TextMeshProUGUI>(4);
            TextMeshProUGUI_Pid = componentItemIndex.Get<TextMeshProUGUI>(5);
            TextMeshProUGUI_Mass = componentItemIndex.Get<TextMeshProUGUI>(6);
            TextMeshProUGUI_Equipment = componentItemIndex.Get<TextMeshProUGUI>(7);
            Button_Close = componentItemIndex.Get<Button>(8);
            Button_Vectors = componentItemIndex.Get<Button>(9);
            Button_Copy = componentItemIndex.Get<Button>(10);
            ScrollRect_Readout = componentItemIndex.Get<ScrollRect>(11);
            UIMenuScope_DroneFlightDebugView = componentItemIndex.Get<UIMenuScope>(12);
        }
    }
}
