// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Core.Runtime.Inputs;
    using TMPro;

    [Source("LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightHudView")]
    public partial class DroneFlightHudView
    {
        public override string Address => "LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightHudView";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private CanvasGroup CanvasGroup_TelemetryRoot;
        private TextMeshProUGUI TextMeshProUGUI_StatusText;
        private TextMeshProUGUI TextMeshProUGUI_CameraText;
        private TextMeshProUGUI TextMeshProUGUI_HeightText;
        private TextMeshProUGUI TextMeshProUGUI_DistanceText;
        private TextMeshProUGUI TextMeshProUGUI_HorizontalText;
        private TextMeshProUGUI TextMeshProUGUI_VerticalText;
        private TextMeshProUGUI TextMeshProUGUI_GearText;
        private RectTransform RectTransform_EquipmentPanel;
        private TextMeshProUGUI TextMeshProUGUI_EquipmentText;
        private TextMeshProUGUI TextMeshProUGUI_EquipmentActions;
        private RectTransform RectTransform_WarningPanel;
        private TextMeshProUGUI TextMeshProUGUI_WarningText;
        private RectTransform RectTransform_ResetPanel;
        private Image Image_ResetProgressFill;
        private UIProgressBar UIProgressBar_ResetProgressFill;
        private TextMeshProUGUI TextMeshProUGUI_ResetProgressText;
        private RectTransform RectTransform_TouchControls;
        private TouchInputPad TouchInputPad_LeftStick;
        private RectTransform RectTransform_Thumb;
        private TouchInputPad TouchInputPad_RightStick;
        private RectTransform RectTransform_Thumb1;
        private InputCommandButton InputCommandButton_ArmOrReset;
        private InputBindingPrompt InputBindingPrompt_Prompt_解锁___长按复位;
        private InputCommandButton InputCommandButton_Equipment;
        private InputBindingPrompt InputBindingPrompt_Prompt_装备操作;
        private InputCommandButton InputCommandButton_Aim;
        private InputBindingPrompt InputBindingPrompt_Prompt_瞄准;
        private InputCommandButton InputCommandButton_ViewModifier;
        private InputBindingPrompt InputBindingPrompt_Prompt_镜头模式;
        private InputCommandButton InputCommandButton_ReelIn;
        private InputBindingPrompt InputBindingPrompt_Prompt_收线;
        private InputCommandButton InputCommandButton_ReelOut;
        private InputBindingPrompt InputBindingPrompt_Prompt_放线;
        private InputCommandButton InputCommandButton_Activate;
        private InputBindingPrompt InputBindingPrompt_Prompt_进入遥控;
        private InputCommandButton InputCommandButton_Back;
        private InputBindingPrompt InputBindingPrompt_Prompt_返回;
        private InputCommandButton InputCommandButton_Panel;
        private InputBindingPrompt InputBindingPrompt_Prompt_操作面板;
        private RectTransform RectTransform_OperationPanel;
        private UIMenuScope UIMenuScope_OperationPanel;
        private InputCommandButton InputCommandButton_Takeoff;
        private InputBindingPrompt InputBindingPrompt_Prompt_自动起飞;
        private InputCommandButton InputCommandButton_Landing;
        private InputBindingPrompt InputBindingPrompt_Prompt_自动降落;
        private InputCommandButton InputCommandButton_ProfileCine;
        private InputBindingPrompt InputBindingPrompt_Prompt_平稳模式;
        private InputCommandButton InputCommandButton_ProfileNormal;
        private InputBindingPrompt InputBindingPrompt_Prompt_普通模式;
        private InputCommandButton InputCommandButton_ProfileSport;
        private InputBindingPrompt InputBindingPrompt_Prompt_运动模式;
        private InputCommandButton InputCommandButton_LandingGear;
        private InputBindingPrompt InputBindingPrompt_Prompt_起落架收放;
        private InputCommandButton InputCommandButton_SwitchCamera;
        private InputBindingPrompt InputBindingPrompt_Prompt_切换镜头;
        private InputCommandButton InputCommandButton_ZoomIn;
        private InputBindingPrompt InputBindingPrompt_Prompt_放大视野;
        private InputCommandButton InputCommandButton_ZoomOut;
        private InputBindingPrompt InputBindingPrompt_Prompt_缩小视野;
        private InputCommandButton InputCommandButton_Help;
        private InputBindingPrompt InputBindingPrompt_Prompt_操作说明;
        private InputCommandButton InputCommandButton_DebugDraw;
        private InputBindingPrompt InputBindingPrompt_Prompt_动力矢量;
        private InputCommandButton InputCommandButton_DebugPanel;
        private InputBindingPrompt InputBindingPrompt_Prompt_调试面板;
        private InputCommandButton InputCommandButton_CopyTelemetry;
        private InputBindingPrompt InputBindingPrompt_Prompt_复制遥测;
        private InputCommandButton InputCommandButton_Exit;
        private InputBindingPrompt InputBindingPrompt_Prompt_返回_Hub;
        private InputCommandButton InputCommandButton_Panel1;
        private InputBindingPrompt InputBindingPrompt_Prompt_关闭面板;
        private InputBindingPrompt InputBindingPrompt_Prompt_确认;
        private InputBindingPrompt InputBindingPrompt_Prompt_返回1;
        private InputCommandButton InputCommandButton_OpenOperations;
        private InputBindingPrompt InputBindingPrompt_Prompt_操作面板1;
        private InputCommandButton InputCommandButton_OpenHelp;
        private InputBindingPrompt InputBindingPrompt_Prompt_操作说明1;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            CanvasGroup_TelemetryRoot = componentItemIndex.Get<CanvasGroup>(0);
            TextMeshProUGUI_StatusText = componentItemIndex.Get<TextMeshProUGUI>(1);
            TextMeshProUGUI_CameraText = componentItemIndex.Get<TextMeshProUGUI>(2);
            TextMeshProUGUI_HeightText = componentItemIndex.Get<TextMeshProUGUI>(3);
            TextMeshProUGUI_DistanceText = componentItemIndex.Get<TextMeshProUGUI>(4);
            TextMeshProUGUI_HorizontalText = componentItemIndex.Get<TextMeshProUGUI>(5);
            TextMeshProUGUI_VerticalText = componentItemIndex.Get<TextMeshProUGUI>(6);
            TextMeshProUGUI_GearText = componentItemIndex.Get<TextMeshProUGUI>(7);
            RectTransform_EquipmentPanel = componentItemIndex.Get<RectTransform>(8);
            TextMeshProUGUI_EquipmentText = componentItemIndex.Get<TextMeshProUGUI>(9);
            TextMeshProUGUI_EquipmentActions = componentItemIndex.Get<TextMeshProUGUI>(10);
            RectTransform_WarningPanel = componentItemIndex.Get<RectTransform>(11);
            TextMeshProUGUI_WarningText = componentItemIndex.Get<TextMeshProUGUI>(12);
            RectTransform_ResetPanel = componentItemIndex.Get<RectTransform>(13);
            Image_ResetProgressFill = componentItemIndex.Get<Image>(14);
            UIProgressBar_ResetProgressFill = componentItemIndex.Get<UIProgressBar>(15);
            TextMeshProUGUI_ResetProgressText = componentItemIndex.Get<TextMeshProUGUI>(16);
            RectTransform_TouchControls = componentItemIndex.Get<RectTransform>(17);
            TouchInputPad_LeftStick = componentItemIndex.Get<TouchInputPad>(18);
            RectTransform_Thumb = componentItemIndex.Get<RectTransform>(19);
            TouchInputPad_RightStick = componentItemIndex.Get<TouchInputPad>(20);
            RectTransform_Thumb1 = componentItemIndex.Get<RectTransform>(21);
            InputCommandButton_ArmOrReset = componentItemIndex.Get<InputCommandButton>(22);
            InputBindingPrompt_Prompt_解锁___长按复位 = componentItemIndex.Get<InputBindingPrompt>(23);
            InputCommandButton_Equipment = componentItemIndex.Get<InputCommandButton>(24);
            InputBindingPrompt_Prompt_装备操作 = componentItemIndex.Get<InputBindingPrompt>(25);
            InputCommandButton_Aim = componentItemIndex.Get<InputCommandButton>(26);
            InputBindingPrompt_Prompt_瞄准 = componentItemIndex.Get<InputBindingPrompt>(27);
            InputCommandButton_ViewModifier = componentItemIndex.Get<InputCommandButton>(28);
            InputBindingPrompt_Prompt_镜头模式 = componentItemIndex.Get<InputBindingPrompt>(29);
            InputCommandButton_ReelIn = componentItemIndex.Get<InputCommandButton>(30);
            InputBindingPrompt_Prompt_收线 = componentItemIndex.Get<InputBindingPrompt>(31);
            InputCommandButton_ReelOut = componentItemIndex.Get<InputCommandButton>(32);
            InputBindingPrompt_Prompt_放线 = componentItemIndex.Get<InputBindingPrompt>(33);
            InputCommandButton_Activate = componentItemIndex.Get<InputCommandButton>(34);
            InputBindingPrompt_Prompt_进入遥控 = componentItemIndex.Get<InputBindingPrompt>(35);
            InputCommandButton_Back = componentItemIndex.Get<InputCommandButton>(36);
            InputBindingPrompt_Prompt_返回 = componentItemIndex.Get<InputBindingPrompt>(37);
            InputCommandButton_Panel = componentItemIndex.Get<InputCommandButton>(38);
            InputBindingPrompt_Prompt_操作面板 = componentItemIndex.Get<InputBindingPrompt>(39);
            RectTransform_OperationPanel = componentItemIndex.Get<RectTransform>(40);
            UIMenuScope_OperationPanel = componentItemIndex.Get<UIMenuScope>(41);
            InputCommandButton_Takeoff = componentItemIndex.Get<InputCommandButton>(42);
            InputBindingPrompt_Prompt_自动起飞 = componentItemIndex.Get<InputBindingPrompt>(43);
            InputCommandButton_Landing = componentItemIndex.Get<InputCommandButton>(44);
            InputBindingPrompt_Prompt_自动降落 = componentItemIndex.Get<InputBindingPrompt>(45);
            InputCommandButton_ProfileCine = componentItemIndex.Get<InputCommandButton>(46);
            InputBindingPrompt_Prompt_平稳模式 = componentItemIndex.Get<InputBindingPrompt>(47);
            InputCommandButton_ProfileNormal = componentItemIndex.Get<InputCommandButton>(48);
            InputBindingPrompt_Prompt_普通模式 = componentItemIndex.Get<InputBindingPrompt>(49);
            InputCommandButton_ProfileSport = componentItemIndex.Get<InputCommandButton>(50);
            InputBindingPrompt_Prompt_运动模式 = componentItemIndex.Get<InputBindingPrompt>(51);
            InputCommandButton_LandingGear = componentItemIndex.Get<InputCommandButton>(52);
            InputBindingPrompt_Prompt_起落架收放 = componentItemIndex.Get<InputBindingPrompt>(53);
            InputCommandButton_SwitchCamera = componentItemIndex.Get<InputCommandButton>(54);
            InputBindingPrompt_Prompt_切换镜头 = componentItemIndex.Get<InputBindingPrompt>(55);
            InputCommandButton_ZoomIn = componentItemIndex.Get<InputCommandButton>(56);
            InputBindingPrompt_Prompt_放大视野 = componentItemIndex.Get<InputBindingPrompt>(57);
            InputCommandButton_ZoomOut = componentItemIndex.Get<InputCommandButton>(58);
            InputBindingPrompt_Prompt_缩小视野 = componentItemIndex.Get<InputBindingPrompt>(59);
            InputCommandButton_Help = componentItemIndex.Get<InputCommandButton>(60);
            InputBindingPrompt_Prompt_操作说明 = componentItemIndex.Get<InputBindingPrompt>(61);
            InputCommandButton_DebugDraw = componentItemIndex.Get<InputCommandButton>(62);
            InputBindingPrompt_Prompt_动力矢量 = componentItemIndex.Get<InputBindingPrompt>(63);
            InputCommandButton_DebugPanel = componentItemIndex.Get<InputCommandButton>(64);
            InputBindingPrompt_Prompt_调试面板 = componentItemIndex.Get<InputBindingPrompt>(65);
            InputCommandButton_CopyTelemetry = componentItemIndex.Get<InputCommandButton>(66);
            InputBindingPrompt_Prompt_复制遥测 = componentItemIndex.Get<InputBindingPrompt>(67);
            InputCommandButton_Exit = componentItemIndex.Get<InputCommandButton>(68);
            InputBindingPrompt_Prompt_返回_Hub = componentItemIndex.Get<InputBindingPrompt>(69);
            InputCommandButton_Panel1 = componentItemIndex.Get<InputCommandButton>(70);
            InputBindingPrompt_Prompt_关闭面板 = componentItemIndex.Get<InputBindingPrompt>(71);
            InputBindingPrompt_Prompt_确认 = componentItemIndex.Get<InputBindingPrompt>(72);
            InputBindingPrompt_Prompt_返回1 = componentItemIndex.Get<InputBindingPrompt>(73);
            InputCommandButton_OpenOperations = componentItemIndex.Get<InputCommandButton>(74);
            InputBindingPrompt_Prompt_操作面板1 = componentItemIndex.Get<InputBindingPrompt>(75);
            InputCommandButton_OpenHelp = componentItemIndex.Get<InputCommandButton>(76);
            InputBindingPrompt_Prompt_操作说明1 = componentItemIndex.Get<InputBindingPrompt>(77);
        }
    }
}
