// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using Hotfix.DroneFlight;
    using TMPro;

    [Source("LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightHudView")]
    public partial class DroneFlightHudView
    {
        public override string Address => "LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightHudView";
        public override UILayer Level => UILayer.Decorate;
        public override UIViewMode ViewMode => UIViewMode.Widget;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private CanvasGroup CanvasGroup_TelemetryRoot;
        private TextMeshProUGUI TextMeshProUGUI_StatusText;
        private TextMeshProUGUI TextMeshProUGUI_CameraText;
        private TextMeshProUGUI TextMeshProUGUI_HeightText;
        private TextMeshProUGUI TextMeshProUGUI_DistanceText;
        private TextMeshProUGUI TextMeshProUGUI_HorizontalText;
        private TextMeshProUGUI TextMeshProUGUI_VerticalText;
        private TextMeshProUGUI TextMeshProUGUI_GearText;
        private RectTransform RectTransform_EquipmentPanel;
        private TextMeshProUGUI TextMeshProUGUI_EquipmentText;
        private TextMeshProUGUI TextMeshProUGUI_EquipmentActions;
        private RectTransform RectTransform_WarningPanel;
        private TextMeshProUGUI TextMeshProUGUI_WarningText;
        private RectTransform RectTransform_ResetPanel;
        private Image Image_ResetProgressFill;
        private TextMeshProUGUI TextMeshProUGUI_ResetProgressText;
        private DroneControlsPresenter DroneControlsPresenter_DroneFlightHudView;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            CanvasGroup_TelemetryRoot = componentItemIndex.Get<CanvasGroup>(0);
            TextMeshProUGUI_StatusText = componentItemIndex.Get<TextMeshProUGUI>(1);
            TextMeshProUGUI_CameraText = componentItemIndex.Get<TextMeshProUGUI>(2);
            TextMeshProUGUI_HeightText = componentItemIndex.Get<TextMeshProUGUI>(3);
            TextMeshProUGUI_DistanceText = componentItemIndex.Get<TextMeshProUGUI>(4);
            TextMeshProUGUI_HorizontalText = componentItemIndex.Get<TextMeshProUGUI>(5);
            TextMeshProUGUI_VerticalText = componentItemIndex.Get<TextMeshProUGUI>(6);
            TextMeshProUGUI_GearText = componentItemIndex.Get<TextMeshProUGUI>(7);
            RectTransform_EquipmentPanel = componentItemIndex.Get<RectTransform>(8);
            TextMeshProUGUI_EquipmentText = componentItemIndex.Get<TextMeshProUGUI>(9);
            TextMeshProUGUI_EquipmentActions = componentItemIndex.Get<TextMeshProUGUI>(10);
            RectTransform_WarningPanel = componentItemIndex.Get<RectTransform>(11);
            TextMeshProUGUI_WarningText = componentItemIndex.Get<TextMeshProUGUI>(12);
            RectTransform_ResetPanel = componentItemIndex.Get<RectTransform>(13);
            Image_ResetProgressFill = componentItemIndex.Get<Image>(14);
            TextMeshProUGUI_ResetProgressText = componentItemIndex.Get<TextMeshProUGUI>(15);
            DroneControlsPresenter_DroneFlightHudView = componentItemIndex.Get<DroneControlsPresenter>(16);
        }
    }
}
