using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using Core.Runtime;
using UnityEditor;
using UnityEngine;

namespace Core.Editor.MvcBind
{
    public static class MvcCodeGenerator
    {
        public static string Generate(MvcBindSettings settings, IReadOnlyList<MvcBindNode> nodes)
        {
            if (string.IsNullOrEmpty(settings.prefabPath))
            {
                throw new InvalidDataException("MvcBind 生成失败：没有检测到 Prefab 资源路径。");
            }

            var components = CollectComponents(nodes);
            if (components.Count == 0)
            {
                throw new InvalidDataException("MvcBind 生成失败：请先在 Hierarchy 勾选至少一个要绑定的组件。");
            }

            settings.outputFolder = MvcBindPathUtility.ToOutputFolder(settings.moduleName, settings.viewName);
            Directory.CreateDirectory(settings.outputFolder);
            var viewPath = Path.Combine(settings.outputFolder, settings.viewScriptName).Replace('\\', '/');
            var componentPath = Path.Combine(settings.outputFolder, settings.componentScriptName).Replace('\\', '/');

            WriteViewScript(settings, components, viewPath);
            WriteComponentScript(settings, components, componentPath);
            AssetDatabase.ImportAsset(viewPath);
            AssetDatabase.ImportAsset(componentPath);
            return $"{viewPath}, {componentPath}";
        }

        private static void WriteComponentScript(MvcBindSettings settings, IReadOnlyList<MvcBindComponentInfo> components, string path)
        {
            File.WriteAllText(path, CreateComponentScriptText(settings, components), new UTF8Encoding(false));
        }

        internal static string CreateComponentScriptText(MvcBindSettings settings, IReadOnlyList<MvcBindComponentInfo> components)
        {
            var isView = settings.viewType == ViewType.View;
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("//     Generated by Tools/MvcBind. Changes will be overwritten.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
            builder.AppendLine("namespace " + settings.namespaceName);
            builder.AppendLine("{");
            builder.AppendLine("    using Core.Runtime;");
            builder.AppendLine("    using UnityEngine;");
            builder.AppendLine("    using UnityEngine.UI;");
            AppendExtraUsing(builder, components);
            builder.AppendLine();
            builder.AppendLine("    [Source(\"" + Escape(settings.address) + "\")]");
            builder.AppendLine("    public partial class " + settings.viewName);
            builder.AppendLine("    {");
            if (isView)
            {
                builder.AppendLine("        public override string Address => \"" + Escape(settings.address) + "\";");
                builder.AppendLine("        public override UILayer Level => UILayer." + settings.layer + ";");
                builder.AppendLine("        public override UIViewMode ViewMode => UIViewMode." + settings.viewMode + ";");
                builder.AppendLine("        public override MaskType Mask => MaskType." + settings.mask + ";");
                builder.AppendLine("        public override bool IsAsync => " + ToLiteral(settings.isAsync) + ";");
                builder.AppendLine("        public override bool EnableOnInit => " + ToLiteral(settings.enableOnInit) + ";");
                builder.AppendLine("        public override bool DestroyOnHide => " + ToLiteral(settings.destroyOnHide) + ";");
                AppendTransitionSettings(builder, settings);
            }

            AppendFields(builder, components);
            AppendInitComponent(builder, components);

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void WriteViewScript(MvcBindSettings settings, IReadOnlyList<MvcBindComponentInfo> components, string path)
        {
            if (!File.Exists(path))
            {
                File.WriteAllText(path, CreateViewScriptText(settings, components), new UTF8Encoding(false));
                return;
            }

            var source = File.ReadAllText(path, Encoding.UTF8);
            var callbacks = BuildMissingCallbackText(source, components);
            if (string.IsNullOrEmpty(callbacks))
            {
                return;
            }

            var insertIndex = FindClassCloseBrace(source, settings.viewName);
            if (insertIndex < 0)
            {
                Debug.LogWarning($"MvcBind 无法在已有脚本中定位 {settings.viewName} 类，已跳过补充回调方法：{path}");
                return;
            }

            source = source.Insert(insertIndex, callbacks);
            File.WriteAllText(path, source, new UTF8Encoding(false));
        }

        private static string CreateViewScriptText(MvcBindSettings settings, IReadOnlyList<MvcBindComponentInfo> components)
        {
            var builder = new StringBuilder();
            builder.AppendLine("namespace " + settings.namespaceName);
            builder.AppendLine("{");
            builder.AppendLine("    using Core.Runtime;");
            builder.AppendLine();
            builder.AppendLine("    [Module(\"" + Escape(settings.moduleName) + "\")]");
            builder.AppendLine("    [Mvc(\"" + Escape(settings.viewName) + "\")]");
            builder.AppendLine("    public partial class " + settings.viewName + " : " + settings.viewType);
            builder.AppendLine("    {");
            if (settings.viewType == ViewType.View)
            {
                builder.AppendLine("        protected override void OnGameObjectInitialize()");
                builder.AppendLine("        {");
                builder.AppendLine("        }");
            }
            AppendCallbackMethods(builder, components, string.Empty);
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        public static List<MvcBindComponentInfo> CollectComponents(IReadOnlyList<MvcBindNode> nodes)
        {
            var components = new List<MvcBindComponentInfo>();
            var fieldNames = new HashSet<string>();
            foreach (var node in nodes)
            {
                var selectedTypes = GetSelectedComponentTypes(node);
                if (selectedTypes.Count == 0)
                {
                    continue;
                }

                foreach (var componentType in selectedTypes)
                {
                    var component = node.gameObject != null ? node.gameObject.GetComponent(componentType) : null;
                    if (component == null)
                    {
                        continue;
                    }

                    var fieldName = ToUniqueFieldName(ToFieldName(componentType, node.name), fieldNames);
                    var info = new MvcBindComponentInfo
                    {
                        index = components.Count,
                        fieldName = fieldName,
                        componentType = componentType,
                        component = component
                    };

                    foreach (var methodName in GetSelectedMethodNames(node, componentType))
                    {
                        var method = FindRegisterMethod(componentType, methodName);
                        if (method != null)
                        {
                            info.methods.Add(method);
                        }
                    }

                    components.Add(info);
                }
            }

            return components;
        }

        private static void AppendFields(StringBuilder builder, IReadOnlyList<MvcBindComponentInfo> components)
        {
            if (components.Count == 0)
            {
                return;
            }

            builder.AppendLine();
            foreach (var component in components)
            {
                builder.AppendLine("        private " + GetTypeName(component.componentType) + " " + component.fieldName + ";");
            }
        }

        private static void AppendTransitionSettings(StringBuilder builder, MvcBindSettings settings)
        {
            if (!string.IsNullOrEmpty(settings.uiTransitionType) && settings.uiTransitionType != "null")
            {
                builder.AppendLine("        protected override IUITransition CreateUITransition()");
                builder.AppendLine("        {");
                builder.AppendLine("            return new " + settings.uiTransitionType + "();");
                builder.AppendLine("        }");
            }

            if (!string.IsNullOrEmpty(settings.worldTransitionKey))
            {
                builder.AppendLine("        public override string WorldTransitionKey => \"" + Escape(settings.worldTransitionKey) + "\";");
            }
        }

        private static void AppendExtraUsing(StringBuilder builder, IReadOnlyList<MvcBindComponentInfo> components)
        {
            var namespaces = new SortedSet<string>();
            foreach (var component in components)
            {
                if (ShouldEmitUsing(component.componentType?.Namespace))
                {
                    namespaces.Add(component.componentType.Namespace);
                }

                foreach (var method in component.methods)
                {
                    foreach (var parameterType in method.parameterTypes)
                    {
                        if (ShouldEmitUsing(parameterType.Namespace))
                        {
                            namespaces.Add(parameterType.Namespace);
                        }
                    }
                }
            }

            foreach (var namespaceName in namespaces)
            {
                builder.AppendLine("    using " + namespaceName + ";");
            }
        }

        private static bool ShouldEmitUsing(string namespaceName)
        {
            return !string.IsNullOrEmpty(namespaceName) &&
                   namespaceName != "Core.Runtime" &&
                   namespaceName != "UnityEngine" &&
                   namespaceName != "UnityEngine.UI";
        }

        private static void AppendInitComponent(StringBuilder builder, IReadOnlyList<MvcBindComponentInfo> components)
        {
            if (components.Count == 0)
            {
                return;
            }

            builder.AppendLine();
            builder.AppendLine("        private ComponentItemIndex componentItemIndex;");
            builder.AppendLine();
            builder.AppendLine("        protected override void InitComponent()");
            builder.AppendLine("        {");
            builder.AppendLine("            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();");
            builder.AppendLine("            if (componentItemIndex == null)");
            builder.AppendLine("            {");
            builder.AppendLine("                return;");
            builder.AppendLine("            }");
            builder.AppendLine();
            foreach (var component in components)
            {
                builder.AppendLine("            " + component.fieldName + " = componentItemIndex.Get<" + GetTypeName(component.componentType) + ">(" + component.index + ");");
            }

            foreach (var component in components)
            {
                foreach (var method in component.methods)
                {
                    builder.AppendLine("            this." + method.componentMethodName + "(" + component.fieldName + ", " + method.registerMethodName + ");");
                }
            }
            builder.AppendLine("        }");
        }

        private static string BuildMissingCallbackText(string source, IReadOnlyList<MvcBindComponentInfo> components)
        {
            var builder = new StringBuilder();
            AppendCallbackMethods(builder, components, source);
            return builder.ToString();
        }

        private static void AppendCallbackMethods(StringBuilder builder, IReadOnlyList<MvcBindComponentInfo> components, string existingSource)
        {
            var emitted = new HashSet<string>();
            foreach (var component in components)
            {
                foreach (var method in component.methods)
                {
                    if (!emitted.Add(method.registerMethodName) || ContainsMethod(existingSource, method.registerMethodName))
                    {
                        continue;
                    }

                    builder.AppendLine();
                    builder.AppendLine("        private void " + method.registerMethodName + "(" + method.parameterText + ")");
                    builder.AppendLine("        {");
                    builder.AppendLine("        }");
                }
            }
        }

        private static bool ContainsMethod(string source, string methodName)
        {
            if (string.IsNullOrEmpty(source))
            {
                return false;
            }

            return Regex.IsMatch(source, $@"\b{Regex.Escape(methodName)}\s*\(");
        }

        private static int FindClassCloseBrace(string source, string className)
        {
            var classMatch = Regex.Match(source, $@"\bclass\s+{Regex.Escape(className)}\b");
            if (!classMatch.Success)
            {
                return -1;
            }

            var openIndex = source.IndexOf('{', classMatch.Index);
            if (openIndex < 0)
            {
                return -1;
            }

            var depth = 0;
            for (var i = openIndex; i < source.Length; i++)
            {
                if (source[i] == '{')
                {
                    depth++;
                    continue;
                }

                if (source[i] != '}')
                {
                    continue;
                }

                depth--;
                if (depth == 0)
                {
                    return i;
                }
            }

            return -1;
        }

        private static string GetTypeName(System.Type type)
        {
            if (type == null)
            {
                return "Component";
            }

            if (type == typeof(int))
            {
                return "int";
            }

            if (type == typeof(bool))
            {
                return "bool";
            }

            if (type == typeof(float))
            {
                return "float";
            }

            if (type == typeof(double))
            {
                return "double";
            }

            if (type == typeof(string))
            {
                return "string";
            }

            if (type == typeof(void))
            {
                return "void";
            }

            return type.Name.Replace('+', '.');
        }

        public static List<MvcBindMethodInfo> GetRegisterMethods(System.Type componentType, string gameObjectName)
        {
            var methods = new List<MvcBindMethodInfo>();
            var emitted = new HashSet<string>();
            if (componentType == null)
            {
                return methods;
            }

            foreach (var method in TypeCache.GetMethodsWithAttribute<ComponentAttribute>())
            {
                if (!method.IsStatic || method.DeclaringType == null)
                {
                    continue;
                }

                var parameters = method.GetParameters();
                if (!IsRegisterMethodForComponent(parameters, componentType))
                {
                    continue;
                }

                var attribute = method.GetCustomAttribute<ComponentAttribute>();
                if (attribute == null)
                {
                    continue;
                }

                var registerMethodName = string.Format(attribute.MethodFormat, gameObjectName);
                var parameterText = GetCallbackParameterText(parameters[2].ParameterType);
                var key = $"{method.Name}|{registerMethodName}|{parameterText}";
                if (!emitted.Add(key))
                {
                    continue;
                }

                methods.Add(new MvcBindMethodInfo
                {
                    registerMethodName = registerMethodName,
                    componentMethodName = method.Name,
                    parameterText = parameterText,
                    parameterTypes = GetCallbackParameterTypes(parameters[2].ParameterType)
                });
            }

            return methods;
        }

        private static MvcBindMethodInfo FindRegisterMethod(System.Type componentType, string registerMethodName)
        {
            foreach (var method in TypeCache.GetMethodsWithAttribute<ComponentAttribute>())
            {
                if (!method.IsStatic || method.DeclaringType == null)
                {
                    continue;
                }

                var parameters = method.GetParameters();
                if (!IsRegisterMethodForComponent(parameters, componentType))
                {
                    continue;
                }

                var attribute = method.GetCustomAttribute<ComponentAttribute>();
                if (attribute == null)
                {
                    continue;
                }

                var prefix = attribute.MethodFormat.Split('{')[0];
                var suffixIndex = attribute.MethodFormat.IndexOf('}');
                var suffix = suffixIndex >= 0 && suffixIndex + 1 < attribute.MethodFormat.Length
                    ? attribute.MethodFormat.Substring(suffixIndex + 1)
                    : string.Empty;
                if (registerMethodName.StartsWith(prefix) && registerMethodName.EndsWith(suffix))
                {
                    return new MvcBindMethodInfo
                    {
                        registerMethodName = registerMethodName,
                        componentMethodName = method.Name,
                        parameterText = GetCallbackParameterText(parameters[2].ParameterType),
                        parameterTypes = GetCallbackParameterTypes(parameters[2].ParameterType)
                    };
                }
            }

            return null;
        }

        private static bool IsRegisterMethodForComponent(ParameterInfo[] parameters, System.Type componentType)
        {
            return parameters.Length == 3 &&
                   (parameters[0].ParameterType.IsAssignableFrom(typeof(View)) ||
                    parameters[0].ParameterType.IsAssignableFrom(typeof(ItemView))) &&
                   parameters[1].ParameterType.IsAssignableFrom(componentType);
        }

        private static string GetCallbackParameterText(System.Type callbackType)
        {
            var invoke = callbackType.GetMethod("Invoke");
            if (invoke == null)
            {
                return string.Empty;
            }

            var parameters = invoke.GetParameters();
            var parts = new List<string>();
            for (int i = 0; i < parameters.Length; i++)
            {
                parts.Add(GetTypeName(parameters[i].ParameterType) + " obj" + (i + 1));
            }

            return string.Join(", ", parts);
        }

        private static List<System.Type> GetCallbackParameterTypes(System.Type callbackType)
        {
            var types = new List<System.Type>();
            var invoke = callbackType.GetMethod("Invoke");
            if (invoke == null)
            {
                return types;
            }

            foreach (var parameter in invoke.GetParameters())
            {
                types.Add(parameter.ParameterType);
            }

            return types;
        }

        private static System.Type ResolveComponentType(string fullName)
        {
            if (string.IsNullOrEmpty(fullName))
            {
                return null;
            }

            foreach (var assembly in System.AppDomain.CurrentDomain.GetAssemblies())
            {
                var type = assembly.GetType(fullName);
                if (type != null)
                {
                    return type;
                }
            }

            return null;
        }

        private static string ToFieldName(System.Type componentType, string gameObjectName)
        {
            return $"{ToIdentifierPart(GetTypeName(componentType))}_{ToIdentifierPart(gameObjectName)}";
        }

        private static string ToIdentifierPart(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return "GameObject";
            }

            var builder = new StringBuilder(value.Length);
            foreach (var ch in value)
            {
                builder.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            }

            if (builder.Length == 0)
            {
                return "GameObject";
            }

            if (char.IsDigit(builder[0]))
            {
                builder.Insert(0, '_');
            }

            return builder.ToString();
        }

        private static string ToUniqueFieldName(string value, HashSet<string> used)
        {
            var candidate = value;
            var suffix = 1;
            while (!used.Add(candidate))
            {
                candidate = $"{value}{suffix++}";
            }

            return candidate;
        }

        private static List<System.Type> GetSelectedComponentTypes(MvcBindNode node)
        {
            var types = new List<System.Type>();
            if (node.selectedComponentTypes.Count > 0)
            {
                types.AddRange(node.selectedComponentTypes);
                return types;
            }

            if (node.selectedComponentType != null)
            {
                types.Add(node.selectedComponentType);
                return types;
            }

            var resolved = ResolveComponentType(node.selectedComponentTypeName);
            if (resolved != null)
            {
                types.Add(resolved);
            }

            return types;
        }

        private static List<string> GetSelectedMethodNames(MvcBindNode node, System.Type componentType)
        {
            if (componentType != null &&
                node.selectedMethodNamesByComponentTypeName.TryGetValue(componentType.FullName, out var methods) &&
                methods.Count > 0)
            {
                return methods;
            }

            return node.selectedMethodNames;
        }

        private static string Escape(string value)
        {
            return (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string ToLiteral(bool value)
        {
            return value ? "true" : "false";
        }
    }
}
