// <auto-generated>
//     Generated by Tools/MvcBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;

    [Source("LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightVehicleSelectView")]
    public partial class DroneFlightVehicleSelectView
    {
        public override string Address => "LoadResources/Demos/drone_flight/Prefabs/UI/DroneFlightVehicleSelectView";
        public override UILayer Level => UILayer.Pop;
        public override UIViewMode ViewMode => UIViewMode.Modal;
        public override MaskType Mask => MaskType.ShowOnly;
        public override bool IsAsync => true;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.FadeScaleUITransition();
        }

        private Button Button_PlainButton;
        private Button Button_GrappleButton;
        private Button Button_HarpoonButton;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            Button_PlainButton = componentItemIndex.Get<Button>(0);
            Button_GrappleButton = componentItemIndex.Get<Button>(1);
            Button_HarpoonButton = componentItemIndex.Get<Button>(2);
            this.RegisterButton(Button_PlainButton, OnPlainButtonClick);
            this.RegisterButton(Button_GrappleButton, OnGrappleButtonClick);
            this.RegisterButton(Button_HarpoonButton, OnHarpoonButtonClick);
        }
    }
}
