// <auto-generated>
//     Generated by Tools/UIBind. Changes will be overwritten.
// </auto-generated>

namespace Hotfix
{
    using Core.Runtime;
    using UnityEngine;
    using UnityEngine.UI;
    using TMPro;

    [Source("LoadResources/Demos/how_to_fish/Prefabs/UI/HowToFishPauseView")]
    public partial class HowToFishPauseView
    {
        public override string Address => "LoadResources/Demos/how_to_fish/Prefabs/UI/HowToFishPauseView";
        public override UILayer Level => UILayer.Tip;
        public override UIViewMode ViewMode => UIViewMode.Modal;
        public override MaskType Mask => MaskType.None;
        public override bool EnableOnInit => true;
        public override bool DestroyOnHide => true;
        protected override IUITransition CreateUITransition()
        {
            return new Core.Runtime.EmptyUITransition();
        }

        private TextMeshProUGUI TextMeshProUGUI_MenuTitle;
        private Button Button_Resume;
        private Button Button_Save;
        private Button Button_ReturnHub;
        private Button Button_OpenOutfits;
        private Button Button_OpenSettings;

        private ComponentItemIndex componentItemIndex;

        protected override void InitComponent()
        {
            componentItemIndex = gameObject.GetComponent<ComponentItemIndex>();
            if (componentItemIndex == null)
            {
                return;
            }

            TextMeshProUGUI_MenuTitle = componentItemIndex.Get<TextMeshProUGUI>(0);
            Button_Resume = componentItemIndex.Get<Button>(1);
            Button_Save = componentItemIndex.Get<Button>(2);
            Button_ReturnHub = componentItemIndex.Get<Button>(3);
            Button_OpenOutfits = componentItemIndex.Get<Button>(4);
            Button_OpenSettings = componentItemIndex.Get<Button>(5);
        }
    }
}
